/*
 * Copyright 2023 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 *     https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
package eu.europa.ec.leos.repository.security.service;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.env.Environment;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import com.auth0.jwt.interfaces.Claim;

import eu.europa.ec.leos.repository.config.PasswordConfigurator;
import eu.europa.ec.leos.repository.security.config.UsernameAuthenticationToken;
import eu.europa.ec.leos.repository.security.model.AuthClient;

@Component
public class JwtTokenService {

	private static final Logger LOG = LoggerFactory.getLogger(JwtTokenService.class);

	@Value("${repository.jwt.auth.issuer.id}")
	private String issuerId;

	@Value("${repository.jwt.auth.issuer.secret}")
	private String issuerSecret;

	@Value("${repository.jwt.auth.access.token.expiration.min}")
	private int accessTokenExpirationInMin;

	@Value("${repository.jwt.auth.clients}")
	private String authClients;
	private List<AuthClient> registeredClients = new ArrayList<>();

	@Autowired
	private Environment environment;

	@Autowired
	private PasswordConfigurator passwordConfigurator;

	@Autowired
	private AuthenticationManager authenticationManager;

	@PostConstruct
	public void init() {
		String[] clientsNames = authClients.split(",");
		String keyPrefix = "repository.jwt.auth.client.";
		for (String clientName : clientsNames) {
			String clientId = environment.getProperty(keyPrefix + clientName + ".id");
			String clientSecret = passwordConfigurator.getProperty(keyPrefix + clientName + ".secret");
			if (!StringUtils.hasText(clientId) || !StringUtils.hasText(clientSecret)) {
				LOG.error("Key 'repository.jwt.auth.clients' and its corresponding clientId/secret is not configured correctly for each single client!!!");
			} else {
				registeredClients.add(new AuthClient(clientName, clientId, clientSecret));
			}
		}
	}

	public AuthClient validateClientWithToken(final String token) {
		for (AuthClient authClient : registeredClients) {
			boolean isValid = isTokenValid(authClient.getClientId(), authClient.getSecret(), token);
			if (isValid) {
				LOG.debug("Valid token generated by client {}", authClient.getName());
				authClient.setVerified(true);
				return authClient;
			}
		}
		return new AuthClient();
	}

	public boolean validateAccessToken(final String token) {
		return isTokenValid(issuerId, issuerSecret, token);
	}

	private boolean isTokenValid(final String issuer, final String secret, final String token) {
		try {
			JWT.require(Algorithm.HMAC256(secret))
					.withIssuer(issuer)
					.acceptExpiresAt(accessTokenExpirationInMin * 60)
					.build()
					.verify(token);
			return true;
		} catch (Exception e) {
			return false;
		}
	}

	public String generateToken(final String issuer, final String secret, final String user) {
		Date now = Calendar.getInstance().getTime();

		Calendar expires = Calendar.getInstance();
		expires.add(Calendar.MINUTE, accessTokenExpirationInMin);
		Date expiresAt = expires.getTime();

		Algorithm algorithm = Algorithm.HMAC256(secret);

		String token = JWT.create()
				.withIssuer(issuer)
				.withIssuedAt(now)
				.withNotBefore(now)
				.withExpiresAt(expiresAt)
				.withClaim("user", user)
				.sign(algorithm);

		return token;
	}

	public String getAccessToken(final String user) {
		return generateToken(issuerId, issuerSecret, user);
	}

	public Long getAccessTokenExpirationIn() {
		return System.currentTimeMillis() + accessTokenExpirationInMin * 60 * 1000;
	}

	public String extractUserFromToken(final String token) {
		Claim claim = JWT.decode(token).getClaim("user");
		if (claim.isNull()) {
			return null;
		}
		return claim.asString();
	}

	public String authenticateUserWithToken(final String token) {
		final String user = this.extractUserFromToken(token);
		UsernameAuthenticationToken usernameAuthenticationToken = new UsernameAuthenticationToken(user);
		authenticationManager.authenticate(usernameAuthenticationToken);
		SecurityContextHolder.getContext().setAuthentication(usernameAuthenticationToken);
		return user;
	}

}
