stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DskipTests=true'
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn/cache"
  GIT_CLEAN_FLAGS: -ffdx -e .yarn -e .m2/repository -e .npm

java-build:
  image: maven:3.8-openjdk-8
  stage: build
  resource_group: cypress
  script:
    - mvn clean install
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - pom.xml
      - "**/target"
      - "**/dist"
      - "**/package-lock.json"
      - "**/yarn.lock"
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2
      - $CI_PROJECT_DIR/.yarn
      - $CI_PROJECT_DIR/.npm
    policy: pull-push

cypress-test-for-local:
  image:
    name: code.europa.eu:4567/leos/core/image-for-tests:1.0.1
  variables:
    TAGS_TO_RUN: "@local"
  stage: test
  dependencies:
    - java-build
  resource_group: cypress
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^Draft.*$/ && $TAGS_TO_RUN == "@local"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - cd $CI_PROJECT_DIR/tools/user-repo
    - mvn clean install
    - cd $CI_PROJECT_DIR/tools/user-repo/web
    - mvn spring-boot:run -Dspring-boot.run.profiles=h2 &
    - cd $CI_PROJECT_DIR/tools/repository
    - mvn clean install
    - cd $CI_PROJECT_DIR/tools/repository/web
    - mvn spring-boot:run -Dspring-boot.run.directories=../config/target/generated-config &
    - cd $CI_PROJECT_DIR
    - mvn clean install
    - cd $CI_PROJECT_DIR/modules/web
    - mvn jetty:run-war &
    - sleep 40
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - npm install
    - npx cypress run --browser chrome --headed -e TAGS="$TAGS_TO_RUN"
  after_script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - node ./cucumberReport.js
  artifacts:
    expire_in: 5 days
    when: always
    paths:
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/screenshots/**/*.png
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/report/**/*.*
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/videos/**/*.*

cypress-test-for-non-local:
  image:
    name: code.europa.eu:4567/leos/core/image-for-tests:1.0.1
  stage: test
  resource_group: cypress
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TAGS_TO_RUN == "@nonlocal"
  script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - npm install
    - npx cypress run --browser chrome --headed -e TAGS="$TAGS_TO_RUN"
  after_script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - node ./cucumberReport.js
  artifacts:
    expire_in: 5 days
    when: always
    paths:
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/screenshots/**/*.png
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/report/**/*.*

include:
  - project: 'digit.s.1/sa/security-scan-template'
    file: '.gitlab-ci-security-scan.yml'
    ref: main
