image: $CI_REGISTRY_IMAGE/image-for-tests:1.0.4

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/$CI_MERGE_REQUEST_ID/.yarn/cache"
  GIT_CLEAN_FLAGS: -ffdx -e .yarn -e .m2/repository -e .npm
  npm_config_cache: '$CI_PROJECT_DIR/$CI_MERGE_REQUEST_ID/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_BUILDS_DIR/$CI_PIPELINE_ID/.m2/repository"

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - $CI_BUILDS_DIR/$CI_PIPELINE_ID/.m2/repository/

java-build:
  stage: build
  script:
    - echo "=== BUILD MVN START ===$(date) ==="
    - cd $CI_PROJECT_DIR/tools/user-repo
    - mvn clean install
    - cd $CI_PROJECT_DIR/tools/repository
    - mvn clean install
#    - cd $CI_PROJECT_DIR/tools/akn4euutil
#    - mvn clean install
    - cd $CI_PROJECT_DIR
    - mvn clean install -DskipKarmaTests -Dleos.log.level=ERROR
    - echo "=== BUILD MVN END ===$(date) ==="
  artifacts:
    expire_in: 4 hour
    when: always
    paths:
      - pom.xml
      - "**/target"
      - "**/package-lock.json"
      - "**/yarn.lock"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TAGS_TO_RUN == "@fortify"
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
  interruptible: true

.cypress-base:
  variables:
    TAGS_TO_RUN: "@local"
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
  needs: [java-build]
  script:
    - echo "=== CYPRESS-BASE MVN INSTALL START ===$(date) ==="
    - cd $CI_PROJECT_DIR/tools/user-repo
    - mvn install -DskipTests
    - cd $CI_PROJECT_DIR/tools/repository
    - mvn install -DskipTests
    - cd $CI_PROJECT_DIR
    - mvn install -DskipTests -DskipKarmaTests -Dleos.log.level=ERROR
    - echo "=== CYPRESS-BASE MVN INSTALL END ===$(date) ==="
    - cd $CI_PROJECT_DIR/tools/user-repo/web
    - mvn spring-boot:run -Dspring-boot.run.profiles=h2 &
    - cd $CI_PROJECT_DIR/tools/repository/web
    - mvn spring-boot:run -Dspring-boot.run.additional-classpath-elements=../config/target/generated-config -Dspring-boot.run.arguments="--logging.level.root=ERROR" &
#    - cd $CI_PROJECT_DIR/tools/akn4euutil/web
#    - mvn spring-boot:run -Dspring-boot.run.additional-classpath-elements=../config/target/generated-config -Dspring-boot.run.jvmArguments="-Dakn4eu.log.level=ERROR" &
    - cd $CI_PROJECT_DIR/modules/web
    - mvn -Dcargo.jvmargs="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Xms512m -Xmx2g" cargo:run &
    - sleep 40
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - npm install
    - npx cypress run --spec "$SPECS" -e CE_ENV="$TAGS_TO_RUN",TAGS="$TAGS_TO_RUN" --browser chrome --headed
  after_script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - node ./cucumberReport.js
    - rm -rf $CI_BUILDS_DIR/$CI_PIPELINE_ID/.m2/repository
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/screenshots/**/*.png
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/report/**/*.*
  interruptible: true

cypress-group-1:
  extends: .cypress-base
  variables:
    SPECS: "cypress/e2e/features/ckEditor.feature,cypress/e2e/features/forkAndMerge.feature"

cypress-group-2:
  extends: .cypress-base
  variables:
    SPECS: "cypress/e2e/features/trackChanges.feature,cypress/e2e/features/annex.feature,cypress/e2e/features/financialStatement.feature,cypress/e2e/features/coverPage.feature,cypress/e2e/features/createAct.feature"

cypress-group-3:
  extends: .cypress-base
  variables:
    SPECS: "cypress/e2e/features/legalAct.feature,cypress/e2e/features/userManagement.feature,cypress/e2e/features/collaborators.feature,cypress/e2e/features/milestones.feature,cypress/e2e/features/actViewer.feature,cypress/e2e/features/expMemo.feature,cypress/e2e/features/homePage.feature,cypress/e2e/features/comparison.feature"

cypress-test-for-non-local:
  variables:
    TAGS_TO_RUN: "@nonlocal"
  stage: test
  resource_group: cypress
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TAGS_TO_RUN == "@nonlocal"
  script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - npm install
    - npx cypress run --quiet --browser chrome --headed -e CE_ENV="dev",TAGS="$TAGS_TO_RUN"
  after_script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - node ./cucumberReport.js
  artifacts:
    expire_in: 1 days
    when: always
    paths:
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/screenshots/**/*.png
      - $CI_PROJECT_DIR/modules/test-cypress/cypress/report/**/*.*

include:
  - project: 'digit.s.1/sa/security-scan-template'
    file: '.gitlab-ci-security-scan.yml'
    ref: 1.0.0

fortify-sast:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec skip|skip sec)\\].*/"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec run|run sec)\\].*/"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^Draft.*$/
      when: never

sonatype-lifecycle:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec skip|skip sec)\\].*/"
      when: never
    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec run|run sec)\\].*/"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^Draft.*$/
      when: never

#fortify-import-issues-ssc:
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"
#      when: never
#    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec skip|skip sec)\\].*/"
#      when: never
#    - if: "$CI_COMMIT_MESSAGE =~ /.*\\[(sec run|run sec)\\].*/"
#      when: always
#    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
#      when: always
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^Draft.*$/
#      when: never

fortify-import-issues-ssc:
  rules:
    - when: never