stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DskipTests=true'
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn/cache"
  GIT_CLEAN_FLAGS: -ffdx -e .yarn -e .m2/repository

cypress-test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  script:
    - cd $CI_PROJECT_DIR/modules/test-cypress
    - npm install
    - npx cypress run
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/modules/test-cypress/videos/**/*.mp4
      - $CI_PROJECT_DIR/modules/test-cypress/screenshots/**/*.png

java-build:
  image: maven:3.8-openjdk-8
  stage: build
  script:
    - mvn clean package
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - "**/target/*.war"
      - "modules/ui-angular/package.json"
      - "modules/ui-angular/yarn.lock"
  cache:
    paths:
    - $CI_PROJECT_DIR/.m2/
    - $CI_PROJECT_DIR/.yarn
    policy: pull-push
  rules:
    - when: always

include:
  - project: 'digit.s.1/sa/security-scan-template'
    file: '.gitlab-ci-security-scan-mvn.yml'
    ref: main

#fortify-sast:
#  image: fcoene/public:fortify-jdk8-node20
#
#sonatype-lifecycle:
#  image: fcoene/public:sonatype-lifecycle-jdk8
