# LOCAL build properties
# NOTE: these properties can override LEOS repository common build properties
repository.default.id=leos_dev
server.servlet.context-path=/repository
spring.datasource.jndi-name=jdbc/leosRepository