package eu.europa.ec.leos.services.utils;

import eu.europa.ec.leos.domain.ai.AnalysisResultDataFlowsGeneration;
import eu.europa.ec.leos.domain.ai.AnalysisResultDataGeneration;
import eu.europa.ec.leos.domain.ai.AnalysisResultDescriptionGeneration;
import eu.europa.ec.leos.domain.ai.AnalysisResultInteroperabilityGeneration;
import eu.europa.ec.leos.domain.ai.AnalysisResultSolutionsGeneration;
import eu.europa.ec.leos.domain.ai.AnalysisResults;
import eu.europa.ec.leos.domain.common.Result;
import eu.europa.ec.leos.domain.repository.document.Bill;
import eu.europa.ec.leos.services.label.ReferenceLabelService;
import eu.europa.ec.leos.services.label.ref.Ref;
import eu.europa.ec.leos.services.support.IdGenerator;
import eu.europa.ec.leos.services.support.XercesUtils;
import eu.europa.ec.leos.services.support.XmlHelper;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static eu.europa.ec.leos.services.support.XmlHelper.LEOS_TC_INSERT_ELEMENT_NAME;
import static eu.europa.ec.leos.services.support.XmlHelper.LEOS_TITLE;
import static eu.europa.ec.leos.services.support.XmlHelper.LEOS_UID;
import static eu.europa.ec.leos.services.support.XmlHelper.MREF;
import static eu.europa.ec.leos.services.support.XmlHelper.XMLID;

@Component
public class AIUtils {
    static String AI_USER = "ai";

    private final ReferenceLabelService referenceLabelService;

    public AIUtils(ReferenceLabelService referenceLabelService) {
        this.referenceLabelService = referenceLabelService;
    }

    private void appendValueNewColumn(Node node, String value) {
        Node tdElt = node.getOwnerDocument().createElement(XmlHelper.TD);
        XercesUtils.addAttribute(tdElt, XMLID, IdGenerator.generateId());
        Node pElt = node.getOwnerDocument().createElement(XmlHelper.P);
        XercesUtils.addAttribute(pElt, XMLID, IdGenerator.generateId());
        if (StringUtils.isNotBlank(value)) {
            appendValueIns(pElt, value);
        } else {
            pElt.setTextContent(" ");
        }
        tdElt.appendChild(pElt);
        node.appendChild(tdElt);
    }

    private void appendValuesNewColumn(Node node, List<String> values) {
        Node tdElt = node.getOwnerDocument().createElement(XmlHelper.TD);
        XercesUtils.addAttribute(tdElt, XMLID, IdGenerator.generateId());
        Node pElt = node.getOwnerDocument().createElement(XmlHelper.P);
        XercesUtils.addAttribute(pElt, XMLID, IdGenerator.generateId());
        if (!values.isEmpty()) {
            appendValueIns(pElt, String.join(", ", values));
        } else {
            pElt.setTextContent(" ");
        }
        tdElt.appendChild(pElt);
        node.appendChild(tdElt);
    }

    private void appendRefsInNewColumn(Node node, List<String> referenceIds, Bill bill, String lfdsRef) {
        Node tdElt = node.getOwnerDocument().createElement(XmlHelper.TD);
        XercesUtils.addAttribute(tdElt, XMLID, IdGenerator.generateId());
        Node pElt = node.getOwnerDocument().createElement(XmlHelper.P);
        XercesUtils.addAttribute(pElt, XMLID, IdGenerator.generateId());
        appendRefsIns(pElt, referenceIds, bill, lfdsRef);
        tdElt.appendChild(pElt);
        node.appendChild(tdElt);
    }

    private void appendValueIns(Node node, String value) {
        Node insElt = node.getOwnerDocument().createElement(LEOS_TC_INSERT_ELEMENT_NAME);
        XercesUtils.addAttribute(insElt, XMLID, IdGenerator.generateId());
        XercesUtils.addAttribute(insElt, LEOS_UID, AI_USER);
        XercesUtils.addAttribute(insElt, LEOS_TITLE, "Generated by AI : " + LocalDateTime.now().toString());
        insElt.setTextContent(value);
        if (isBlank(node)) {
            node.setTextContent("");
        }
        node.appendChild(insElt);
    }

    private void appendValuesIns(Node node, List<String> values) {
        for (int i=0; i< values.size(); i++) {
            String value = values.get(i);
            if (i>0) {
                Node seperatorNode = node.getOwnerDocument().createTextNode(", ");
                node.appendChild(seperatorNode);
            }
            Node insElt = node.getOwnerDocument().createElement(LEOS_TC_INSERT_ELEMENT_NAME);
            XercesUtils.addAttribute(insElt, XMLID, IdGenerator.generateId());
            XercesUtils.addAttribute(insElt, LEOS_UID, AI_USER);
            XercesUtils.addAttribute(insElt, LEOS_TITLE, "Generated by AI : " + LocalDateTime.now().toString());
            insElt.setTextContent(value);
            if (isBlank(node)) {
                node.setTextContent("");
            }
            node.appendChild(insElt);
        }
    }

    private void appendRefsIns(Node node, List<String> referenceIds, Bill bill, String lfdsRef) {
        for (int i=0; i< referenceIds.size(); i++) {
            String id = referenceIds.get(i);
            if (i>0) {
                Node seperatorNode = node.getOwnerDocument().createTextNode(", ");
                node.appendChild(seperatorNode);
            }
            Node insElt = node.getOwnerDocument().createElement(LEOS_TC_INSERT_ELEMENT_NAME);
            XercesUtils.addAttribute(insElt, XMLID, IdGenerator.generateId());
            XercesUtils.addAttribute(insElt, LEOS_UID, AI_USER);
            XercesUtils.addAttribute(insElt, LEOS_TITLE, "Generated by AI : " + LocalDateTime.now().toString());
            appendNodeMref(insElt, bill.getMetadata().get().getRef(), id, lfdsRef);
            if (isBlank(node)) {
                node.setTextContent("");
            }
            node.appendChild(insElt);
        }
    }

    private void insertValueInNthColumn(Node row, NodeList columns, int n, String value) {
        if (value == null) {
            return;
        }
        if (columns.getLength() > n) {
            if (StringUtils.isNotBlank(value)) {
                appendValueIns(XercesUtils.getFirstChild(columns.item(n)), value);
            }
        } else {
            appendValueNewColumn(row, value);
        }
    }

    private void insertValuesInNthColumn(Node row, NodeList columns, int n, List<String> values) {
        if (values == null || values.isEmpty()) {
            return;
        }
        if (columns.getLength() > n) {
            appendValuesIns(XercesUtils.getFirstChild(columns.item(n)), values);
        } else {
            appendValuesNewColumn(row, values);
        }
    }

    private void insertIdsInNthColumn(Node row, NodeList columns, int n, List<String> referenceIds, Bill bill, String lfdsRef) {
        if (referenceIds == null || referenceIds.isEmpty()) {
            return;
        }
        if (columns.getLength() > n) {
            appendRefsIns(XercesUtils.getFirstChild(columns.item(n)), referenceIds, bill, lfdsRef);
        } else {
            appendRefsInNewColumn(row, referenceIds, bill, lfdsRef);
        }
    }

    // Checks if a row or a column is empty
    private boolean isBlank(Node node) {
        return StringUtils.isBlank(node.getTextContent().replaceAll("[\\n|\\s|\\u00A0]", ""));
    }

    // Checks if a row or a column is not empty
    private boolean isNotBlank(Node node) {
        return StringUtils.isNotBlank(node.getTextContent().replaceAll("[\\n|\\s|\\u00A0]", ""));
    }

    private boolean doesContainsValue(Node node, String value) {
        return value == null || node.getTextContent().toLowerCase().contains(value.toLowerCase());
    }

    private boolean doesContainsValues(Node node, List<String> values) {
        for (String value : values) {
            if (value != null && !node.getTextContent().toLowerCase().contains(value.toLowerCase())) {
                return false;
            }
        }
        return true;
    }

    private boolean doesContainsRefs(Node node, List<String> ids, Bill bill) {
        for (String id : ids) {
            final String value = referenceLabelService.generateLabelStringRef(Arrays.asList(id),
                    bill.getMetadata().get().getRef(), bill.getContent().get().getSource().getBytes()).get();
            if (value != null && !node.getTextContent().toLowerCase().contains(value.toLowerCase())) {
                return false;
            }
        }
        return true;
    }

    // Method to remove already present descriptions' results
    private List<AnalysisResultDescriptionGeneration> filterDescriptionGenerations(Element table, List<AnalysisResultDescriptionGeneration> newResults,
                                                                                   Bill bill) {
        NodeList rows = XercesUtils.getElementsByName(table, XmlHelper.TR);
        for (int i = 1; i < rows.getLength(); i++) {
            Node row = rows.item(i);
            if (isNotBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                for (int index = 0; index < newResults.size(); index++) {
                    AnalysisResultDescriptionGeneration newResult = newResults.get(index);
                    if (columns.getLength() > 3
                            && doesContainsRefs(columns.item(0), newResult.getEId(), bill)
                            && doesContainsValue(columns.item(1), newResult.getDescription())
                            && doesContainsValues(columns.item(2), newResult.getActors())
                            && doesContainsValues(columns.item(3), newResult.getHigh_level_process())) {
                        newResults.remove(index);
                        index--;
                    }
                }
            }
        }
        return newResults;
    }

    // Method to add descriptions' results in XML
    private void addPrefillTextInTableDescriptionGenerations(Element table, List<AnalysisResultDescriptionGeneration> newResults, Bill bill, String lfdsRef) {
        List<AnalysisResultDescriptionGeneration> results = filterDescriptionGenerations(table, newResults, bill);
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        int resultIndex = 0;
        for (int i = 1; i < rows.getLength(); i++) {
            if (resultIndex >= results.size()) break;
            Node row = rows.item(i);
            if (isBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                AnalysisResultDescriptionGeneration result = results.get(resultIndex);
                insertIdsInNthColumn(row, columns, 0, result.getEId(), bill, lfdsRef);
                insertValueInNthColumn(row, columns, 1, result.getDescription());
                insertValuesInNthColumn(row, columns, 2, result.getActors());
                insertValuesInNthColumn(row, columns, 3, result.getHigh_level_process());
                resultIndex++;
            }
        }
        for (int i = resultIndex; i < results.size(); i++) {
            AnalysisResultDescriptionGeneration result = results.get(i);
            Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
            XercesUtils.addAttribute(trElt, XMLID, IdGenerator.generateId());
            appendRefsInNewColumn(trElt, result.getEId(), bill, lfdsRef);
            appendValueNewColumn(trElt, result.getDescription());
            appendValuesNewColumn(trElt, result.getActors());
            appendValuesNewColumn(trElt, result.getHigh_level_process());
            table.appendChild(trElt);
        }
    }

    // Method to remove already present data' results
    private List<AnalysisResultDataGeneration> filterDataGenerations(Element table, List<AnalysisResultDataGeneration> newResults, Bill bill) {
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            Node row = rows.item(i);
            if (isNotBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                for (int index=0; index<newResults.size(); index++) {
                    AnalysisResultDataGeneration newResult = newResults.get(index);
                    if (columns.getLength() > 2
                            && doesContainsValue(columns.item(0), newResult.getType_of_data())
                            && doesContainsRefs(columns.item(1), newResult.getEId(), bill)
                            && doesContainsValues(columns.item(2), newResult.getStandard())) {
                        newResults.remove(index);
                        index--;
                    }
                }
            }
        }
        return newResults;
    }

    // Method to add data's results in XML
    private void addPrefillTextInTableDataGenerations(Element table, List<AnalysisResultDataGeneration> newResults, Bill bill, String lfdsRef) {
        List<AnalysisResultDataGeneration> results = this.filterDataGenerations(table, newResults, bill);
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        int resultIndex = 0;
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            if (resultIndex >= results.size()) break;
            Node row = rows.item(i);
            if (isBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                AnalysisResultDataGeneration result = results.get(resultIndex);
                insertValueInNthColumn(row, columns,0, result.getType_of_data());
                insertIdsInNthColumn(row, columns, 1, result.getEId(), bill, lfdsRef);
                insertValuesInNthColumn(row, columns, 2, result.getStandard());
                resultIndex++;
            }
        }
        for (int i = resultIndex; i < results.size(); i++) {
            AnalysisResultDataGeneration result = results.get(i);
            Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
            XercesUtils.addAttribute(trElt, XMLID, IdGenerator.generateId());
            appendValueNewColumn(trElt, result.getType_of_data());
            appendRefsInNewColumn(trElt, result.getEId(), bill, lfdsRef);
            appendValuesNewColumn(trElt, result.getStandard());
            table.appendChild(trElt);
        }
    }

    // Method to remove already present solutions' results
    private List<AnalysisResultSolutionsGeneration> filterSolutionsGenerations(Element table, List<AnalysisResultSolutionsGeneration> newResults, Bill bill) {
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            Node row = rows.item(i);
            if (isNotBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                for (int index=0; index<newResults.size(); index++) {
                    AnalysisResultSolutionsGeneration newResult = newResults.get(index);
                    if (columns.getLength() > 3
                            && doesContainsValue(columns.item(0), newResult.getDigital_solution())
                            && doesContainsRefs(columns.item(1), newResult.getEId(), bill)
                            && doesContainsValues(columns.item(2), newResult.getFunctionalities())
                            && doesContainsValue(columns.item(3), newResult.getResponsible_actor())) {
                        newResults.remove(index);
                        index--;
                    }
                }
            }
        }
        return newResults;
    }

    // Method to add solutions' results in XML
    private void addPrefillTextInTableSolutionGenerations(Element table, List<AnalysisResultSolutionsGeneration> newResults, Bill bill, String lfdsRef) {
        List<AnalysisResultSolutionsGeneration> results = this.filterSolutionsGenerations(table, newResults, bill);
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        int resultIndex = 0;
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            if (resultIndex >= results.size()) break;
            Node row = rows.item(i);
            if (isBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row, XmlHelper.TD);
                AnalysisResultSolutionsGeneration result = results.get(resultIndex);
                insertValueInNthColumn(row, columns, 0, result.getDigital_solution());
                insertIdsInNthColumn(row, columns, 1, result.getEId(), bill, lfdsRef);
                insertValuesInNthColumn(row, columns, 2, result.getFunctionalities());
                insertValueInNthColumn(row, columns, 3, result.getResponsible_actor());
                insertValueInNthColumn(row, columns, 4, " ");
                insertValueInNthColumn(row, columns, 5, " ");
                insertValueInNthColumn(row, columns, 6, " ");
                resultIndex++;
            }
        }
        for (int i = resultIndex; i < results.size(); i++) {
            AnalysisResultSolutionsGeneration result = results.get(i);
            Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
            XercesUtils.addAttribute(trElt, XMLID, IdGenerator.generateId());
            appendValueNewColumn(trElt, result.getDigital_solution());
            appendRefsInNewColumn(trElt, result.getEId(), bill, lfdsRef);
            appendValuesNewColumn(trElt, result.getFunctionalities());
            appendValueNewColumn(trElt, result.getResponsible_actor());
            appendValueNewColumn(trElt, " ");
            appendValueNewColumn(trElt, " ");
            appendValueNewColumn(trElt, " ");
            table.appendChild(trElt);
        }
    }

    // Method to remove already present generations' results
    private List<AnalysisResultInteroperabilityGeneration> filterInterGenerations(Node table, List<AnalysisResultInteroperabilityGeneration> newResults,
                                                                                  Bill bill) {
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            Node row = rows.item(i);
            if (isNotBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
                for (int index=0; index<newResults.size(); index++) {
                    AnalysisResultInteroperabilityGeneration newResult = newResults.get(index);
                    if (columns.getLength() > 4
                            && doesContainsValue(columns.item(0), newResult.getDigital_public_service())
                            && doesContainsValue(columns.item(1), newResult.getDescription())
                            && doesContainsRefs(columns.item(2), newResult.getEId(), bill)
                            && doesContainsValue(columns.item(3), newResult.getInteroperable_europe_solutions())
                            && doesContainsValues(columns.item(4), newResult.getOther_interoperability_solutions())) {
                        newResults.remove(index);
                        index--;
                    }
                }
            }
        }
        return newResults;
    }

    // Method to add generations' results in XML
    private void addPrefillTextInTableInterGenerations(Element table, List<AnalysisResultInteroperabilityGeneration> newResults, Bill bill, String lfdsRef) {
        List<AnalysisResultInteroperabilityGeneration> results = this.filterInterGenerations(table, newResults, bill);
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        int resultIndex = 0;
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            if (resultIndex >= results.size()) break;
            Node row = rows.item(i);
            if (isBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
                AnalysisResultInteroperabilityGeneration result = results.get(resultIndex);
                insertValueInNthColumn(row, columns, 0, result.getDigital_public_service());
                insertValueInNthColumn(row, columns, 1, result.getDescription());
                insertIdsInNthColumn(row, columns, 2, result.getEId(), bill, lfdsRef);
                insertValueInNthColumn(row, columns, 3, result.getInteroperable_europe_solutions());
                insertValuesInNthColumn(row, columns, 4, result.getOther_interoperability_solutions());
                resultIndex++;
            }
        }
        for (int i = resultIndex; i < results.size(); i++) {
            AnalysisResultInteroperabilityGeneration result = results.get(i);
            Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
            XercesUtils.addAttribute(trElt, XMLID, IdGenerator.generateId());
            appendValueNewColumn(trElt, result.getDigital_public_service());
            appendValueNewColumn(trElt, result.getDescription());
            appendRefsInNewColumn(trElt, result.getEId(), bill, lfdsRef);
            appendValueNewColumn(trElt, result.getInteroperable_europe_solutions());
            appendValuesNewColumn(trElt, result.getOther_interoperability_solutions());
            table.appendChild(trElt);
        }
    }

    private void addPrefillTextInTableSubInterGenerations(Element table, List<AnalysisResultInteroperabilityGeneration> results) {
        Optional<AnalysisResultInteroperabilityGeneration> result1 = results.stream().filter((r) -> r.getLegal_interoperability_measures() != null
                && r.getLegal_interoperability_measures().policies != null
                && !r.getLegal_interoperability_measures().policies.isEmpty()).findFirst();

        Optional<AnalysisResultInteroperabilityGeneration> result2 = results.stream().filter(r -> r.getOrganisational_interoperability_measures() != null
                && r.getOrganisational_interoperability_measures().measures != null
                && !r.getOrganisational_interoperability_measures().measures.isEmpty()).findFirst();

        Optional<AnalysisResultInteroperabilityGeneration> result3 = results.stream().filter(r -> r.getSemantic_interoperability_measures() != null
                && r.getSemantic_interoperability_measures().measures != null
                && !r.getSemantic_interoperability_measures().measures.isEmpty()).findFirst();

        Optional<AnalysisResultInteroperabilityGeneration> result4 = results.stream().filter(r -> r.getTechnical_interoperability_measures() != null
                && r.getTechnical_interoperability_measures().measures != null
                && !r.getTechnical_interoperability_measures().measures.isEmpty()).findFirst();

        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        if ((result1.isPresent()
                || result2.isPresent()
                || result3.isPresent()
                || result4.isPresent())
                && rows.getLength()<5) {
            for (int i=rows.getLength(); i<5; i++) {
                Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
                appendValueNewColumn(trElt, " ");
                appendValueNewColumn(trElt, " ");
                appendValueNewColumn(trElt, " ");
                table.appendChild(trElt);
            }
        }
        if (result1.isPresent()) {
            Node row = rows.item(1);
            NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
            for (int i=columns.getLength(); i<3; i++) {
                appendValueNewColumn(row, " ");
            }
            if (StringUtils.isBlank(columns.item(0).getTextContent().replaceAll(Pattern.quote("\n"), ""))) {
                columns.item(0).setTextContent("<b>Alignment with existing digital and sectorial policies.</b>");
            }
            List<String> policies =
                    result1.get().getLegal_interoperability_measures().policies.stream().filter(p -> !columns.item(1).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(1)), String.join(", ", policies));
            List<String> legal_barriers =
                    result1.get().getLegal_interoperability_measures().legal_barriers.stream().filter(p -> !columns.item(2).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(2)), String.join(", ", legal_barriers));
        }
        if (result2.isPresent()) {
            Node row = rows.item(2);
            NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
            for (int i=columns.getLength(); i<3; i++) {
                appendValueNewColumn(row, " ");
            }
            if (StringUtils.isBlank(columns.item(0).getTextContent().replaceAll(Pattern.quote("\n"), ""))) {
                columns.item(0).setTextContent("<b>Organisational measures for a smooth cross-border digital public.</b>");
            }
            List<String> measures =
                    result2.get().getOrganisational_interoperability_measures().measures.stream().filter(p -> !columns.item(1).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(1)), String.join(", ", measures));
            List<String> organisational_barriers =
                    result2.get().getOrganisational_interoperability_measures().organisational_barriers.stream().filter(p -> !columns.item(2).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(2)), String.join(", ", organisational_barriers));
        }
        if (result3.isPresent()) {
            Node row = rows.item(3);
            NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
            for (int i=columns.getLength(); i<3; i++) {
                appendValueNewColumn(row, " ");
            }
            if (StringUtils.isBlank(columns.item(0).getTextContent().replaceAll(Pattern.quote("\n"), ""))) {
                columns.item(0).setTextContent("<b>Measures taken to ensure a shared understanding of the data.</b>");
            }
            List<String> measures =
                    result3.get().getSemantic_interoperability_measures().measures.stream().filter(p -> !columns.item(1).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(1)), String.join(", ", measures));
            List<String> semantic_barriers =
                    result3.get().getSemantic_interoperability_measures().semantic_barriers.stream().filter(p -> !columns.item(2).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(2)), String.join(", ", semantic_barriers));
        }
        if (result4.isPresent()) {
            Node row = rows.item(4);
            NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
            for (int i=columns.getLength(); i<3; i++) {
                appendValueNewColumn(row, " ");
            }
            if (StringUtils.isBlank(columns.item(0).getTextContent().replaceAll(Pattern.quote("\n"), ""))) {
                columns.item(0).setTextContent("<b>Use of commonly agreed open technical specifications and standards.</b>");
            }
            List<String> measures =
                    result4.get().getTechnical_interoperability_measures().measures.stream().filter(p -> !columns.item(1).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(1)), String.join(", ", measures));
            List<String> technical_barriers =
                    result4.get().getTechnical_interoperability_measures().technical_barriers.stream().filter(p -> !columns.item(2).getTextContent().toLowerCase().contains(p.toLowerCase())).collect(Collectors.toList());
            appendValueIns(XercesUtils.getFirstChild(columns.item(2)), String.join(", ", technical_barriers));
        }
    }

    // Method to remove already present data flows' results
    private List<AnalysisResultDataFlowsGeneration> filterFlowsGenerations(Node table, List<AnalysisResultDataFlowsGeneration> newResults, Bill bill) {
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            Node row = rows.item(i);
            if (isNotBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
                for (int index=0; index<newResults.size(); index++) {
                    AnalysisResultDataFlowsGeneration newResult = newResults.get(index);
                    if (columns.getLength() > 4
                            && doesContainsRefs(columns.item(1), newResult.getEId(), bill)
                            && doesContainsValue(columns.item(2), newResult.getAddresser())
                            && doesContainsValue(columns.item(3), newResult.getAddressee())
                            && doesContainsValue(columns.item(4), newResult.getAction_result())) {
                        newResults.remove(index);
                        index--;
                    }
                }
            }
        }
        return newResults;
    }

    private void addPrefillTextInTableFlowsGenerations(Node table, List<AnalysisResultDataFlowsGeneration> newResults, Bill bill, String lfdsRef) {
        List<AnalysisResultDataFlowsGeneration> results = this.filterFlowsGenerations(table, newResults, bill);
        NodeList rows = XercesUtils.getElementsByName(table,XmlHelper.TR);
        int resultIndex = 0;
        for (int i=1; i<rows.getLength(); i++) { // Skipping header
            if (resultIndex >= results.size()) break;
            Node row = rows.item(i);
            if (isBlank(row)) {
                NodeList columns = XercesUtils.getElementsByName(row,XmlHelper.TD);
                AnalysisResultDataFlowsGeneration result = results.get(resultIndex);
                insertValueInNthColumn(row, columns, 0, " ");
                insertIdsInNthColumn(row, columns, 1, result.getEId(), bill, lfdsRef);
                insertValueInNthColumn(row, columns, 2, result.getAddresser());
                insertValueInNthColumn(row, columns, 3, result.getAddressee());
                insertValueInNthColumn(row, columns, 4, result.getAction_result());
                insertValueInNthColumn(row, columns, 5, " ");
                resultIndex++;
            }
        }
        for (int i = resultIndex; i < results.size(); i++) {
            AnalysisResultDataFlowsGeneration result = results.get(i);
            Node trElt = table.getOwnerDocument().createElement(XmlHelper.TR);
            XercesUtils.addAttribute(trElt, XMLID, IdGenerator.generateId());
            appendValueNewColumn(trElt, " ");
            appendRefsInNewColumn(trElt, result.getEId(), bill, lfdsRef);
            appendValueNewColumn(trElt, result.getAddresser());
            appendValueNewColumn(trElt, result.getAddressee());
            appendValueNewColumn(trElt, result.getAction_result());
            appendValueNewColumn(trElt, " ");
            table.appendChild(trElt);
        }
    }

    // Method to find specific table in XML
    private Element findNthTableInLevel(Document doc, String levelNumber, int n) {
        // Find correct level thanks to numbering
        String xpath = "//akn:" + XmlHelper.NUM + "[text()='" + levelNumber + "']";
        NodeList levelNums = XercesUtils.getElementsByXPath(doc, xpath);
        if (levelNums.getLength() > 0) {
            Node levelNum = levelNums.item(0);
            NodeList tables = XercesUtils.getElementsByName(levelNum.getParentNode(), XmlHelper.TABLE);
            if (tables.getLength() > n) {
                return (Element) tables.item(n);
            }
        }
        return null;
    }

    // Main method to insert AI track changes in XML
    public byte[] insertPrefillElementsInXml(AnalysisResults data, byte[] xml, Bill bill, String lfdsRef) {
        if (data == null) {
            return xml;
        }
        Document doc = XercesUtils.createXercesDocument(xml, true);
        if (data.getDescGenerationResults() != null && !data.getDescGenerationResults().isEmpty()) {
            Element table = findNthTableInLevel(doc, "4.1.", 0);
            if (table != null) {
                addPrefillTextInTableDescriptionGenerations(table, data.getDescGenerationResults(), bill, lfdsRef);
            }
        }
        if (data.getDataGenerationResults() != null && !data.getDataGenerationResults().isEmpty()) {
            Element table = findNthTableInLevel(doc, "4.2.", 0);
            if (table != null) {
                addPrefillTextInTableDataGenerations(table, data.getDataGenerationResults(), bill, lfdsRef);
            }
        }
        if (data.getSolutionsGenerationResults() != null && !data.getSolutionsGenerationResults().isEmpty()) {
            Element table = findNthTableInLevel(doc, "4.3.", 0);
            if (table != null) {
                addPrefillTextInTableSolutionGenerations(table, data.getSolutionsGenerationResults(), bill, lfdsRef);
            }
        }
        if (data.getInterGenerationResults() != null && !data.getInterGenerationResults().isEmpty()) {
            Element table = findNthTableInLevel(doc, "4.4.", 0);
            if (table!=null) {
                this.addPrefillTextInTableInterGenerations(table, data.getInterGenerationResults(), bill, lfdsRef);
            }
            table = this.findNthTableInLevel(doc, "4.4.", 1);
            if (table!=null) {
                this.addPrefillTextInTableSubInterGenerations(table, data.getInterGenerationResults());
            }
        }
        if (data.getDataFlowsGenerationResults() != null && !data.getDataFlowsGenerationResults().isEmpty()) {
            Element table = findNthTableInLevel(doc, "4.2.", 1);
            if (table != null) {
                this.addPrefillTextInTableFlowsGenerations(table, data.getDataFlowsGenerationResults(), bill, lfdsRef);
            }
        }
        return XercesUtils.nodeToByteArray(doc);
    }

    private void appendNodeMref(Node node, String billRef, String id, String lfdsRef) {
        Node mrefNode = node.getOwnerDocument().createElement(MREF);
        XercesUtils.addAttribute(mrefNode, XMLID, IdGenerator.generateId());
        node.appendChild(mrefNode);
        Ref ref = new Ref(IdGenerator.generateId(), id, billRef, null);
        Result<String> result = this.referenceLabelService.generateLabel(Arrays.asList(ref), lfdsRef, XercesUtils.getId(node), node.getOwnerDocument(),
                true);
        XercesUtils.addContentToNode(mrefNode, result.get());
    }
}
