INSERT INTO CONFIG (ID,NAME,OBJECT_ID,AUDIT_C_BY,AUDIT_C_DATE,AUDIT_LAST_M_BY,AUDIT_LAST_M_DATE,ORIGINAL_ID,REPOSITORY_ID,LANGUAGE) VALUES (1,'PR-025',0,
    'doe',to_timestamp('06-APR-23 12:26:17.000000000','DD-MON-RR HH24:MI:SSXFF'),null,null,0,1,'EN');

INSERT INTO REPOSITORY (ID,CMIS_ID,NAME,DESCRIPTION,ALL_VERSIONS_SEARCHABLE,AUDIT_C_BY,AUDIT_C_DATE,AUDIT_LAST_M_BY,AUDIT_LAST_M_DATE) VALUES (1,0,'LEOS',
    'LEOS reporitory',0,'doe',to_timestamp('06-APR-23 12:26:17.000000000','DD-MON-RR HH24:MI:SSXFF'),null,null);

INSERT INTO CONFIG_CATEGORIES (ID,CATEGORY_CODE,CATEGORY_DESC,AUDIT_C_BY,AUDIT_C_DATE,AUDIT_LAST_M_BY,AUDIT_LAST_M_DATE,CATEGORY_TYPE) VALUES (1,'CONFIG',
    'Configuration','doe',to_timestamp('06-APR-23 12:26:17.000000000','DD-MON-RR HH24:MI:SSXFF'),null,null,'CONFIG');
