CREATE TABLE PERMISSION
(   ID NUMBER(22,0) IDENTITY,
    NAME VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(100 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

CREATE TABLE ACL
(   ID NUMBER(22,0) IDENTITY,
    IS_DIRECT NUMBER(1,0),
    OBJECT_ID NUMBER(22,0),
    PERMISSION_ID NUMBER(22,0),
    PRINCIPAL_ID VARCHAR2(100 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

CREATE TABLE CHANGE_EVENT
(   ID NUMBER(22,0) IDENTITY,
    DOCUMENT_ID NUMBER(22,0),
    CHANGE_TYPE VARCHAR2(100 BYTE),
    CHANGE_LOG_TOKEN VARCHAR2(100 BYTE),
    CHANGE_TIME TIMESTAMP (6),
    USERNAME VARCHAR2(100 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

CREATE TABLE DOCUMENT_CATEGORIES
(    ID NUMBER(22,0) IDENTITY,
     CATEGORY_CODE VARCHAR2(30 BYTE),
     CATEGORY_DESC VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE DOCUMENT_MILESTONE
(   ID NUMBER(22,0) IDENTITY,
    DOCUMENT_ID NUMBER(22,0),
    JOB_DATE DATE,
    MILESTONE_COMMENTS VARCHAR2(4000 BYTE),
    CONTENT BLOB,
    STATUS VARCHAR2(30 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    JOB_ID VARCHAR2(100 BYTE)
);

CREATE TABLE DOCUMENT_MILESTONE_COMMENTS
(   ID NUMBER(22,0) IDENTITY,
    MILESTONE_ID NUMBER(22,0),
    COMMENTS VARCHAR2(4000 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE DOCUMENT_MILESTONE_LIST
(   ID NUMBER(22,0) IDENTITY,
    MILESTONE_ID NUMBER(22,0),
    CONTAINED_DOCUMENTS VARCHAR2(4000 BYTE),
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE DOCUMENT_PROPERTIES
(	ID NUMBER(22,0) IDENTITY,
     PROPERTY_NAME VARCHAR2(30 BYTE),
     DOC_CATEGORY_ID NUMBER(22,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE DOCUMENT_PROPERTY_VALUES
(	ID NUMBER(22,0) IDENTITY,
     DOCUMENT_ID NUMBER(22,0),
     PROPERTY_ID NUMBER(22,0),
     PROPERTY_VALUE VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     VERSION_ID NUMBER(22,0)
);

CREATE TABLE PACKAGE
(	ID NUMBER(22,0) IDENTITY,
     OBJECT_ID NUMBER,
     NAME VARCHAR2(400 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE CONFIG_CONTENT
(	VERSION_ID NUMBER(22,0),
     CONTENT CLOB,
     CONTENT_STREAM_MIME_TYPE VARCHAR2(4000 BYTE),
     CONTENT_STREAM_FILENAME VARCHAR2(4000 BYTE),
     CONTENT_STREAM_ID VARCHAR2(4000 BYTE),
     CONTENT_STREAM_LENGTH VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(4000 BYTE),
     AUDIT_C_DATE TIMESTAMP (9),
     AUDIT_LAST_M_DATE TIMESTAMP (9),
     AUDIT_LAST_M_BY VARCHAR2(4000 BYTE),
     ID NUMBER(22,0) IDENTITY
);

CREATE TABLE CONFIG_VERSION
(	ID NUMBER(22,0) IDENTITY,
     CONFIG_ID NUMBER(22,0),
     VERSION_LABEL VARCHAR2(100 BYTE),
     VERSION_SERIES_ID VARCHAR2(400 BYTE),
     VERSION_TYPE VARCHAR2(100 BYTE),
     IS_LATEST_MAJOR_VERSION NUMBER(1,0),
     IS_LATEST_VERSION NUMBER(1,0),
     IS_MAJOR_VERSION NUMBER(1,0),
     IS_VERSION_SERIES_CHECKED_OUT NUMBER(1,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     IS_IMMUTABLE NUMBER(1,0)
);

CREATE TABLE DOCUMENT_VERSION
(	ID NUMBER(22,0) IDENTITY,
     VERSION_LABEL VARCHAR2(100 BYTE),
     VERSION_SERIES_ID VARCHAR2(400 BYTE),
     VERSION_TYPE VARCHAR2(100 BYTE),
     COMMENTS VARCHAR2(4000),
     IS_LATEST_MAJOR_VERSION NUMBER(1,0),
     IS_LATEST_VERSION NUMBER(1,0),
     IS_MAJOR_VERSION NUMBER(1,0),
     IS_VERSION_SERIES_CHECKED_OUT NUMBER(1,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (9) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (9),
     IS_IMMUTABLE NUMBER,
     DOCUMENT_ID NUMBER(22,0)
);

CREATE TABLE CONFIG_CATEGORIES
(	ID NUMBER(22,0) IDENTITY,
     CATEGORY_CODE VARCHAR2(30 BYTE),
     CATEGORY_DESC VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     CATEGORY_TYPE VARCHAR2(40 BYTE)
);

CREATE TABLE CONFIG
(	ID NUMBER(22,0) IDENTITY,
     NAME VARCHAR2(100 BYTE),
     OBJECT_ID NUMBER,
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     CATEGORY_ID NUMBER(22,0),
     LANGUAGE VARCHAR2(10 BYTE)
);

CREATE TABLE DOCUMENT
(	ID NUMBER(22,0) IDENTITY,
     OBJECT_ID NUMBER,
     PACKAGE_ID NUMBER(22,0),
     CATEGORY_ID NUMBER(22,0),
     NAME VARCHAR2(400 BYTE),
     CLONED_FROM VARCHAR2(400 BYTE),
     REVISION_STATUS VARCHAR2(30 BYTE),
     CONTRIBUTION_STATUS VARCHAR2(30 BYTE),
     ORIGIN_REF VARCHAR2(30 BYTE),
     BASE_REVISION_ID VARCHAR2(400 BYTE),
     LIVE_DIFFING_REQUIRED NUMBER(1,0),
     REF VARCHAR2(400 BYTE),
     PROCEDURE_TYPE VARCHAR2(100 BYTE),
     DOC_TEMPLATE VARCHAR2(400 BYTE),
     LANGUAGE VARCHAR2(10 BYTE),
     DOC_STAGE VARCHAR2(400 BYTE),
     IS_PRIVATE_WORKING_COPY NUMBER(1,0),
     IS_ARCHIVED NUMBER(1,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

CREATE TABLE DOCUMENT_CONTENT
(	ID NUMBER(22,0) IDENTITY,
     VERSION_ID NUMBER(22,0),
     CATEGORY_CODE VARCHAR2(100 BYTE),
     CONTENT CLOB,
     ACT_TYPE VARCHAR2(100 BYTE),
     DOC_PURPOSE VARCHAR2(400 BYTE),
     DOC_TYPE VARCHAR2(400 BYTE),
     EEA_RELEVANCE NUMBER(1,0),
     TEMPLATE VARCHAR2(400 BYTE),
     TITLE VARCHAR2(400 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

CREATE TABLE COLLABORATORS
(
    ID NUMBER(22,0) IDENTITY,
    COLLABORATOR_NAME VARCHAR2(100) NOT NULL,
    ROLE_ID VARCHAR2(100) NOT NULL,
    ORGANIZATION VARCHAR2(100) NOT NULL,
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    CONSTRAINT COLLABORATORS_PK PRIMARY KEY (ID)
);

CREATE TABLE PACKAGE_COLLABORATORS
(
    ID NUMBER(22,0) IDENTITY,
    PACKAGE_ID NUMBER(22,0),
    COLLABORATOR_ID NUMBER(22,0) NOT NULL,
    IS_FAVORITE NUMBER DEFAULT 0,
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    CONSTRAINT PACKAGE_COLLABORATORS_PK PRIMARY KEY (ID),
    CONSTRAINT PACKAGE_COLLABORATORS_FK FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE (ID),
    CONSTRAINT PACKAGE_COLLABORATORS_FK2 FOREIGN KEY (COLLABORATOR_ID) REFERENCES COLLABORATORS (ID)
);

CREATE INDEX PACKAGE_COLLABORATORS_IDX ON PACKAGE_COLLABORATORS (PACKAGE_ID);
CREATE INDEX PACKAGE_COLLABORATORS_IDX2 ON PACKAGE_COLLABORATORS (COLLABORATOR_ID);

CREATE VIEW DOCUMENT_CATEGORIES_V (ID, CATEGORY_CODE, CATEGORY_DESC, AUDIT_C_BY, AUDIT_C_DATE, AUDIT_LAST_M_BY, AUDIT_LAST_M_DATE) AS
SELECT ID,CATEGORY_CODE,CATEGORY_DESC,AUDIT_C_BY,AUDIT_C_DATE,AUDIT_LAST_M_BY,AUDIT_LAST_M_DATE FROM DOCUMENT_CATEGORIES;

CREATE VIEW DOCUMENT_V  AS
SELECT doc.id||'_'||docver.id||'_'||doccat.id unique_id
     , doc.id document_id,doc.object_id doc_object_id,doc.category_id
     , doc.package_id, pkg.name package_name, docxml.version_id
     , doccat.category_code, doccat.category_desc
     , doc.name, doc.cloned_from,doc.revision_status,doc.contribution_status,doc.origin_ref,doc.base_revision_id,doc.live_diffing_required,doc.ref,doc.procedure_type,doc.doc_template,doc.language,doc.doc_stage,doc.is_private_working_copy
     , docver.audit_c_by doc_audit_c_by,docver.audit_c_date doc_audit_c_date,docver.audit_last_m_date doc_audit_last_m_date,docver.audit_last_m_by doc_audit_last_m_by
     , docver.version_label, docver.version_series_id, docver.version_type, docver.is_latest_major_version, docver.is_latest_version, docver.is_major_version, docver.is_version_series_checked_out
     , docxml.act_type, docxml.doc_purpose, docxml.doc_type, docxml.eea_relevance, docxml.template, docxml.title, docver.comments, doc.is_archived, (SELECT
                                                                                                                                                             count(*) FROM document_property_values dpv WHERE dpv.version_id = docver.id) AS num_props
FROM document doc, document_version docver, document_content docxml, document_categories_v doccat, "PACKAGE" pkg
WHERE docver.DOCUMENT_ID = doc.ID
  AND docver.id = docxml.version_id
  AND doc.category_id = doccat.id AND doc.package_id = pkg.id;

CREATE VIEW MILESTONE_V AS
SELECT doc.id||'_'||docmil.id unique_id, doc.id document_id,doc.package_id,pkg.name package_name,doc.object_id doc_object_id,doc.category_id,doccat.category_code,doc.name,doc.cloned_from,doc.revision_status,doc.contribution_status,doc.origin_ref,doc.base_revision_id,doc.live_diffing_required,doc.ref,doc.procedure_type,
       doc.doc_template,doc.language,doc.doc_stage,doc.is_private_working_copy,doc.audit_c_by doc_audit_c_by,doc.audit_c_date doc_audit_c_date,doc.audit_last_m_date doc_audit_last_m_date,doc.audit_last_m_by doc_audit_last_m_by, docmil.id milestone_id, docmil.job_id, docmil.job_date, docmil.milestone_comments,
       docmil.status,docmil.audit_c_by,docmil.audit_c_date, docmil.audit_last_m_date, docmil.audit_last_m_by
FROM document doc, document_milestone docmil, "PACKAGE" pkg, document_categories doccat
WHERE doc.id = docmil.document_id AND doc.category_id = doccat.id AND doc.package_id = pkg.id;

CREATE VIEW MILESTONE_COMMENTS_V as
SELECT milv.milestone_id||'_'||milcom.id unique_id, milv.package_id, milv.document_id, milv.milestone_id
     , milcom.comments, milcom.audit_c_by, milcom.audit_c_date, milcom.audit_last_m_date, milcom.audit_last_m_by
FROM milestone_v milv, document_milestone_comments milcom
WHERE milv.milestone_id = milcom.milestone_id;

CREATE VIEW MILESTONE_LIST_V as
SELECT milv.milestone_id||'_'||millis.id unique_id, milv.package_id, milv.document_id, milv.milestone_id
     , millis.contained_documents, millis.audit_c_by, millis.audit_c_date, millis.audit_last_m_date, millis.audit_last_m_by
FROM milestone_v milv, document_milestone_list millis
WHERE milv.milestone_id = millis.milestone_id;

CREATE VIEW CONFIGURATION_V as
SELECT conf.id||'_'||ver.id||'_'||con.id||'_'||cat.id unique_id, conf.ID, CONF.NAME, CONF.OBJECT_ID,
       ver.config_id,cat.category_code, cat.category_desc, ver.version_label,ver.version_series_id,ver.version_type,ver.is_latest_major_version,ver.is_latest_version,ver.is_major_version,ver.is_version_series_checked_out,ver.audit_c_by,ver.audit_c_date,ver.audit_last_m_by,ver.audit_last_m_date,ver.is_immutable
        , con.content,con.content_stream_mime_type,con.content_stream_filename,con.content_stream_id,con.content_stream_length
FROM config conf, config_version ver, config_content con, config_categories cat
WHERE
  conf.id = ver.config_id
  and ver.id = con.version_id and cat.id = conf.category_id;

CREATE VIEW DOCUMENT_PROPERTIES_V as
SELECT doc.id||'_'||cat.id||'_'||docver.id||'_'||pro.id||'_'||proval.id unique_id, doc.id,doc.object_id,doc.package_id,doc.category_id,cat.category_code,cat.category_desc,doc.name
     , proval.version_id, docver.version_label,docver.version_series_id,docver.version_type
     , pro.id prop_id,pro.property_name
     , proval.id prop_value_id,proval.property_value,proval.audit_c_by,proval.audit_c_date,proval.audit_last_m_by,proval.audit_last_m_date
FROM document doc, document_categories cat, document_version docver, document_properties pro, document_property_values proval
WHERE doc.category_id = cat.id
  AND cat.id = pro.doc_category_id
  AND doc.id = proval.document_id
  AND pro.id = proval.property_id
  AND proval.version_id = docver.id
  AND doc.id = docver.document_id;

CREATE UNIQUE INDEX CONFIGURATION_PK ON CONFIG (ID);

CREATE UNIQUE INDEX PERMISSION_PK ON PERMISSION (ID);

CREATE UNIQUE INDEX ACL_PK ON ACL (ID);

CREATE UNIQUE INDEX CHANGE_EVENT_PK ON CHANGE_EVENT (ID);

CREATE UNIQUE INDEX DOCUMENT_CATEGORIES_PK ON DOCUMENT_CATEGORIES (ID);

CREATE UNIQUE INDEX DOCUMENT_CATEGORIES_CHK_UQ ON DOCUMENT_CATEGORIES (CATEGORY_CODE);

CREATE UNIQUE INDEX PROPOSAL_PK ON PACKAGE (ID);

CREATE UNIQUE INDEX DOCUMENT_MILESTONE_PK ON DOCUMENT_MILESTONE (ID);

CREATE INDEX DOC_MILESTONE_DOC_IDX ON DOCUMENT_MILESTONE (DOCUMENT_ID);

CREATE UNIQUE INDEX DOCUMENT_MILESTONE_COMMENTS_PK ON DOCUMENT_MILESTONE_COMMENTS (ID);

CREATE INDEX DOC_MIL_COMMENTS_MIL_IDX ON DOCUMENT_MILESTONE_COMMENTS (MILESTONE_ID);

CREATE UNIQUE INDEX DOCUMENT_MILESTONE_LIST_PK ON DOCUMENT_MILESTONE_LIST (ID);

CREATE INDEX DOC_MIL_LIST_MIL_IDX ON DOCUMENT_MILESTONE_LIST (MILESTONE_ID);

CREATE UNIQUE INDEX DOCUMENT_VERSIONS_PK ON DOCUMENT_VERSION (ID);

CREATE INDEX DOC_VERSIONS_LMV_IDX ON DOCUMENT_VERSION (IS_LATEST_MAJOR_VERSION);

CREATE INDEX DOC_VERSIONS_LAV_IDX ON DOCUMENT_VERSION (IS_LATEST_VERSION);

CREATE INDEX DOC_VERSIONS_MAV_IDX ON DOCUMENT_VERSION (IS_MAJOR_VERSION);

CREATE INDEX DOC_VERSIONS_VCO_IDX ON DOCUMENT_VERSION (IS_VERSION_SERIES_CHECKED_OUT);

CREATE UNIQUE INDEX DOCUMENT_PROPERTIES_PK ON DOCUMENT_PROPERTIES (ID);

CREATE INDEX DOC_PRO_CAT_IDX ON DOCUMENT_PROPERTIES (DOC_CATEGORY_ID);

CREATE UNIQUE INDEX DOCUMENT_PROPERTY_VALUES_PK ON DOCUMENT_PROPERTY_VALUES (ID);

CREATE INDEX DOC_PROVAL_DOC_IDX ON DOCUMENT_PROPERTY_VALUES (DOCUMENT_ID);

CREATE INDEX DOC_PROVAL_VER_IDX ON DOCUMENT_PROPERTY_VALUES (VERSION_ID);

CREATE INDEX DOC_PROVAL_PRO_IDX ON DOCUMENT_PROPERTY_VALUES (PROPERTY_ID);

CREATE UNIQUE INDEX CONFIGURATION_CATEGORIES_PK ON CONFIG_CATEGORIES (ID);

CREATE UNIQUE INDEX CONFIG_VERSIONS_PK ON CONFIG_VERSION (ID);

CREATE UNIQUE INDEX CONTENT_PK ON CONFIG_CONTENT (ID);

CREATE UNIQUE INDEX DOCUMENT_METADATA_PK ON DOCUMENT (ID);

CREATE UNIQUE INDEX DOCUMENT_XML_PK ON DOCUMENT_CONTENT (ID);

ALTER TABLE DOCUMENT_PROPERTIES ADD CONSTRAINT DOCUMENT_PROPERTIES_FK2 FOREIGN KEY (DOC_CATEGORY_ID)
    REFERENCES DOCUMENT_CATEGORIES (ID);

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_METADATA_FK3 FOREIGN KEY (CATEGORY_ID)
    REFERENCES DOCUMENT_CATEGORIES (ID);

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_CAT_FK FOREIGN KEY (CATEGORY_CODE)
    REFERENCES DOCUMENT_CATEGORIES (CATEGORY_CODE);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS ADD CONSTRAINT DOCUMENT_MILESTONE_COMMENTS_FK FOREIGN KEY (MILESTONE_ID)
    REFERENCES DOCUMENT_MILESTONE (ID);

ALTER TABLE DOCUMENT_MILESTONE_LIST ADD CONSTRAINT DOCUMENT_MILESTONE_LIST_FK FOREIGN KEY (MILESTONE_ID)
    REFERENCES DOCUMENT_MILESTONE (ID);

ALTER TABLE DOCUMENT_PROPERTY_VALUES ADD CONSTRAINT DOCUMENT_PROPERTY_VALUES_FK2 FOREIGN KEY (PROPERTY_ID)
    REFERENCES DOCUMENT_PROPERTIES (ID);

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_METADATA_FK FOREIGN KEY (PACKAGE_ID)
    REFERENCES PACKAGE (ID);

ALTER TABLE DOCUMENT_PROPERTY_VALUES ADD CONSTRAINT DOC_PROPERTY_VAL_FK FOREIGN KEY (VERSION_ID)
    REFERENCES DOCUMENT_VERSION (ID);

ALTER TABLE CONFIG_CONTENT ADD CONSTRAINT CONFIGURATION_CONTENT_FK FOREIGN KEY (VERSION_ID)
    REFERENCES CONFIG_VERSION (ID);

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_FK FOREIGN KEY (VERSION_ID)
    REFERENCES DOCUMENT_VERSION (ID);

ALTER TABLE PERMISSION MODIFY (ID NOT NULL);

ALTER TABLE PERMISSION MODIFY (NAME NOT NULL);

ALTER TABLE PERMISSION MODIFY (DESCRIPTION NOT NULL);

ALTER TABLE PERMISSION MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE PERMISSION MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE ACL MODIFY (ID NOT NULL);

ALTER TABLE ACL MODIFY (IS_DIRECT NOT NULL);

ALTER TABLE ACL MODIFY (OBJECT_ID NOT NULL);

ALTER TABLE ACL MODIFY (PERMISSION_ID NOT NULL);

ALTER TABLE ACL MODIFY (PRINCIPAL_ID NOT NULL);

ALTER TABLE ACL MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE ACL MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (ID NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (DOCUMENT_ID NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_TYPE NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_LOG_TOKEN NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_TIME NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (USERNAME NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE CHANGE_EVENT MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (CATEGORY_CODE NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (CATEGORY_DESC NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (AUDIT_C_DATE NOT NULL);



ALTER TABLE DOCUMENT_MILESTONE MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (DOCUMENT_ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (JOB_DATE NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (STATUS NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (MILESTONE_ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (MILESTONE_ID NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (CONTAINED_DOCUMENTS NOT NULL);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (PROPERTY_NAME NOT NULL);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (DOC_CATEGORY_ID NOT NULL);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (DOCUMENT_ID NOT NULL);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (PROPERTY_ID NOT NULL);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE PACKAGE MODIFY (ID NOT NULL);

ALTER TABLE PACKAGE MODIFY (OBJECT_ID NOT NULL);

ALTER TABLE PACKAGE MODIFY (NAME NOT NULL);

ALTER TABLE PACKAGE MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE PACKAGE MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE CONFIG_CONTENT MODIFY (VERSION_ID NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (ID NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (CONFIG_ID NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (VERSION_SERIES_ID NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (IS_LATEST_MAJOR_VERSION NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (IS_LATEST_VERSION NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (IS_MAJOR_VERSION NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (IS_VERSION_SERIES_CHECKED_OUT NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE CONFIG_VERSION MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (VERSION_SERIES_ID NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_LATEST_MAJOR_VERSION NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_LATEST_VERSION NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_MAJOR_VERSION NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_VERSION_SERIES_CHECKED_OUT NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_VERSION MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE CONFIG_CATEGORIES MODIFY (ID NOT NULL);

ALTER TABLE CONFIG_CATEGORIES MODIFY (CATEGORY_CODE NOT NULL);

ALTER TABLE CONFIG_CATEGORIES MODIFY (CATEGORY_DESC NOT NULL);

ALTER TABLE CONFIG_CATEGORIES MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE CONFIG_CATEGORIES MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE CONFIG MODIFY (ID NOT NULL);

ALTER TABLE CONFIG MODIFY (NAME NOT NULL);

ALTER TABLE CONFIG MODIFY (OBJECT_ID NOT NULL);

ALTER TABLE CONFIG MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE CONFIG MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_CATEGORY_TYPE_FK FOREIGN KEY (CATEGORY_ID)
    REFERENCES CONFIG_CATEGORIES (ID);

ALTER TABLE DOCUMENT MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT MODIFY (PACKAGE_ID NOT NULL);

ALTER TABLE DOCUMENT MODIFY (CATEGORY_ID NOT NULL);

ALTER TABLE DOCUMENT MODIFY (NAME NOT NULL);

ALTER TABLE DOCUMENT MODIFY (REF NOT NULL);

ALTER TABLE DOCUMENT MODIFY (DOC_TEMPLATE NOT NULL);

ALTER TABLE DOCUMENT MODIFY (LANGUAGE NOT NULL);

ALTER TABLE DOCUMENT MODIFY (DOC_STAGE NOT NULL);

ALTER TABLE DOCUMENT MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (DOC_PURPOSE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (DOC_TYPE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (TEMPLATE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (TITLE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (AUDIT_C_BY NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (AUDIT_C_DATE NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (CONTENT NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (ID NOT NULL);

ALTER TABLE DOCUMENT_CONTENT MODIFY (VERSION_ID NOT NULL);

ALTER TABLE DOCUMENT_CATEGORIES ADD CONSTRAINT DOCUMENT_CATEGORIES_CHK_UQ UNIQUE (CATEGORY_CODE);