app.name=User Repo
app.version=@project.version@
app.build.planName=@ci.shortPlanName@
app.build.number=@ci.buildNumber@
app.build.plan.revision=@ci.planRepository.revision@
app.build.timestamp=@ci.buildTimeStamp@
app.build.repo.url=@ci.repo.url@
app.build.repo.name=@ci.repo.name@
app.build.repo.branchName=@ci.repository.branch.name@
