DROP TABLE IF EXISTS LEOS_SPECIAL_USER_ENTITY CASCADE;
DROP TABLE IF EXISTS LEOS_SPECIAL_USER_ROLE CASCADE;
DROP TABLE IF EXISTS LEOS_SPECIAL_ENTITY CASCADE;
DROP TABLE IF EXISTS LEOS_SPECIAL_USER CASCADE;
DROP TABLE IF EXISTS LEOS_ROLE CASCADE;
DROP TABLE IF EXISTS LEOS_USER_MVIEW CASCADE;
DROP TABLE IF EXISTS LEOS_ENTITY_MVIEW CASCADE;
DROP TABLE IF EXISTS LEOS_ENTITY_CAB_MVIEW CASCADE;
DROP VIEW IF EXISTS LEOS_USER_ENTITY;
DROP VIEW IF EXISTS LEOS_ENTITY;
DROP VIEW IF EXISTS LEOS_USER_ROLE;
DROP VIEW IF EXISTS LEOS_USER;
DROP SEQUENCE IF EXISTS LEOS_SPECIAL_ENTITY_SEQ;
DROP ALIAS IF EXISTS deAccent;
DROP ALIAS IF EXISTS REGEXP_COUNT;

CREATE TABLE LEOS_ROLE
(
    ROLE_NAME VARCHAR2(50 CHAR),
    ROLE_DESC VARCHAR2(50 CHAR),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_NAME)
);

CREATE TABLE LEOS_SPECIAL_USER
(
    USER_LOGIN     VARCHAR2(50 CHAR),
    USER_PER_ID    NUMBER(8,0) NOT NULL,
    USER_LASTNAME  VARCHAR2(50 CHAR),
    USER_FIRSTNAME VARCHAR2(50 CHAR),
    USER_EMAIL     VARCHAR2(320 CHAR),
    JOB_TITLE      VARCHAR2(320 CHAR),
    DATE_CREATED   DATE,
    CONSTRAINT PK_LEOS_SPECIAL_USER PRIMARY KEY (USER_LOGIN)
);

CREATE TABLE LEOS_USER_MVIEW
(
    USER_LOGIN     VARCHAR2(50 CHAR),
    USER_PER_ID    NUMBER(8,0) NOT NULL,
    USER_LASTNAME  VARCHAR2(50 CHAR),
    USER_FIRSTNAME VARCHAR2(50 CHAR),
    USER_EMAIL     VARCHAR2(320 CHAR),
    JOB_TITLE      VARCHAR2(320 CHAR),
    DATE_CREATED   DATE,
    CONSTRAINT PK_LEOS_COMREF_USER PRIMARY KEY (USER_LOGIN)
);

CREATE TABLE LEOS_SPECIAL_USER_ROLE
(
    USER_LOGIN VARCHAR2(50 CHAR),
    ROLE_NAME  VARCHAR2(50 CHAR),
    CONSTRAINT PK_LEOS_USER_ROLE PRIMARY KEY (USER_LOGIN, ROLE_NAME)
);

ALTER TABLE LEOS_SPECIAL_USER_ROLE
    ADD CONSTRAINT FK_LEOS_USER_ROLE_LEOS_ROLE FOREIGN KEY (ROLE_NAME)
        REFERENCES LEOS_ROLE (ROLE_NAME) ON DELETE CASCADE;

ALTER TABLE LEOS_SPECIAL_USER_ROLE
    ADD CONSTRAINT FK_LEOS_USER_ROLE_LEOS_USER FOREIGN KEY (USER_LOGIN)
        REFERENCES LEOS_SPECIAL_USER (USER_LOGIN) ON DELETE CASCADE;

CREATE VIEW LEOS_USER_ROLE AS SELECT * FROM LEOS_SPECIAL_USER_ROLE;

CREATE TABLE LEOS_SPECIAL_ENTITY
(
    ENTITY_ID        VARCHAR2(40 CHAR),
    ENTITY_NAME      VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_PARENT_ID VARCHAR2(20 CHAR),
    ENTITY_ORG_NAME  VARCHAR2(4000 CHAR) NOT NULL,
    CONSTRAINT PK_SPECIAL_LEOS_ENTITY PRIMARY KEY (ENTITY_ID)
);

ALTER TABLE LEOS_SPECIAL_ENTITY
    ADD CONSTRAINT FK_SPECIAL_ENTITY_PARENT FOREIGN KEY (ENTITY_PARENT_ID)
        REFERENCES LEOS_SPECIAL_ENTITY (ENTITY_ID) ON DELETE CASCADE;

CREATE TABLE LEOS_SPECIAL_USER_ENTITY
(
    USER_LOGIN VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_ID  VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT PK_SPECIAL_UE PRIMARY KEY (USER_LOGIN, ENTITY_ID)
);

ALTER TABLE LEOS_SPECIAL_USER_ENTITY
    ADD CONSTRAINT FK_SPECIAL_UE_SPECIAL_USER FOREIGN KEY (USER_LOGIN)
        REFERENCES LEOS_SPECIAL_USER (USER_LOGIN) ON DELETE CASCADE;

ALTER TABLE LEOS_SPECIAL_USER_ENTITY
    ADD CONSTRAINT FK_SPECIAL_UE_SPECIAL_ENTITY FOREIGN KEY (ENTITY_ID)
        REFERENCES LEOS_SPECIAL_ENTITY (ENTITY_ID) ON DELETE CASCADE;

create table LEOS_ENTITY_MVIEW
(
    ENTITY_ID        VARCHAR2(40 CHAR),
    ENTITY_NAME      VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_PARENT_ID VARCHAR2(20 CHAR),
    ENTITY_ORG_NAME  VARCHAR2(4000 CHAR) NOT NULL
);
create table LEOS_ENTITY_CAB_MVIEW
(
    ENTITY_ID        VARCHAR2(40 CHAR),
    ENTITY_NAME      VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_PARENT_ID VARCHAR2(20 CHAR),
    ENTITY_ORG_NAME  VARCHAR2(4000 CHAR) NOT NULL
);
CREATE VIEW LEOS_ENTITY ("ENTITY_ID", "ENTITY_NAME", "ENTITY_PARENT_ID", "ENTITY_ORG_NAME", "ENTITY_IS_CABINET") AS
        SELECT ENTITY_ID, ENTITY_NAME, ENTITY_PARENT_ID, ENTITY_ORG_NAME, 0 AS ENTITY_IS_CABINET FROM LEOS_SPECIAL_ENTITY
    UNION ALL
        SELECT ENTITY_ID, ENTITY_NAME, ENTITY_PARENT_ID, ENTITY_ORG_NAME, 0 AS ENTITY_IS_CABINET FROM LEOS_ENTITY_MVIEW
    UNION ALL
        SELECT ENTITY_ID, ENTITY_NAME, ENTITY_PARENT_ID, ENTITY_ORG_NAME, 1 AS ENTITY_IS_CABINET FROM LEOS_ENTITY_CAB_MVIEW;

CREATE VIEW LEOS_USER_ENTITY AS
        SELECT USER_LOGIN, ENTITY_ID FROM LEOS_SPECIAL_USER_ENTITY
    UNION ALL
        SELECT ENTITY_NAME AS USER_LOGIN, MAX(ENTITY_ID) AS ENTITY_ID FROM LEOS_ENTITY GROUP BY ENTITY_NAME;

CREATE ALIAS IF NOT EXISTS REGEXP_COUNT AS '
  int regexpCount(String input, String pattern) {
      if (input == null || pattern == null) return 0;
      java.util.regex.Matcher m = java.util.regex.Pattern.compile(pattern).matcher(input);
      int count = 0;
      while (m.find()) count++;
      return count;
  }
  ';

CREATE VIEW LEOS_USER ("USER_LOGIN", "USER_PER_ID", "USER_LASTNAME", "USER_FIRSTNAME", "USER_EMAIL", "JOB_TITLE", "DATE_CREATED", "SPECIAL")
    AS SELECT "USER_LOGIN","USER_PER_ID","USER_LASTNAME","USER_FIRSTNAME","USER_EMAIL","JOB_TITLE","DATE_CREATED", TRUE
       FROM LEOS_SPECIAL_USER
    UNION ALL
        SELECT"USER_LOGIN","USER_PER_ID","USER_LASTNAME","USER_FIRSTNAME","USER_EMAIL","JOB_TITLE","DATE_CREATED", FALSE
        FROM LEOS_USER_MVIEW
    UNION ALL
        SELECT
            DISTINCT(ENTITY_NAME) AS USER_LOGIN,
            -1 AS USER_PER_ID,
            NULL AS USER_LASTNAME,
            ENTITY_NAME AS USER_FIRSTNAME,
            'entity@mail.com' AS USER_EMAIL,
            NULL AS JOB_TITLE,
            NULL AS DATE_CREATED,
            FALSE AS SPECIAL
    FROM LEOS_ENTITY WHERE ENTITY_IS_CABINET = 0 OR (ENTITY_IS_CABINET = 1 AND REGEXP_COUNT(ENTITY_NAME, '\.') < 2);

CREATE
ALIAS deAccent AS '
  String deAccent(String value) throws Exception{
      return value.toUpperCase();
  }
';

CREATE SEQUENCE LEOS_SPECIAL_ENTITY_SEQ START WITH 1000000000 INCREMENT BY 1;
