export const ITEM_NAME_ACTION_ID = 'ITEM_NAME_ACTION_ID';
export const MOVE_ACTION_ID = 'MOVE_ACTION_ID';
export const DELETE_ACTION_ID = 'DELETE_ACTION_ID';
export const CROSSHEADING_CHANGE_TYPE_ACTION_ID =
  'CROSSHEADING_CHANGE_TYPE_ACTION_ID';
export const CROSSHEADING_CHANGE_TYPE_NO_GRAPHIC_ID =
  'CROSSHEADING_CHANGE_TYPE_NO_GRAPHIC_ID';
export const CROSSHEADING_CHANGE_TYPE_BULLET_NUM_ID =
  'CROSSHEADING_CHANGE_TYPE_BULLET_NUM_ID';
export const CROSSHEADING_CHANGE_TYPE_INDENT_ID =
  'CROSSHEADING_CHANGE_TYPE_INDENT_ID';
export const DIVISION_CHANGE_TYPE_ACTION_ID = 'DIVISION_CHANGE_TYPE_ACTION_ID';
export const DIVISION_CHANGE_TYPE_1_ID = 'DIVISION_CHANGE_TYPE_1_ID';
export const DIVISION_CHANGE_TYPE_2_ID = 'DIVISION_CHANGE_TYPE_2_ID';
export const DIVISION_CHANGE_TYPE_3_ID = 'DIVISION_CHANGE_TYPE_3_ID';
export const DIVISION_CHANGE_TYPE_4_ID = 'DIVISION_CHANGE_TYPE_4_ID';
export const POINT_CHANGE_TYPE_ACTION_ID = 'POINT_CHANGE_TYPE_ACTION_ID';
export const POINT_CHANGE_TYPE_NO_GRAPHIC_ID =
  'POINT_CHANGE_TYPE_NO_GRAPHIC_ID';
export const POINT_CHANGE_TYPE_LONG_INDENT_ID =
  'POINT_CHANGE_TYPE_LONG_INDENT_ID';
export const POINT_CHANGE_TYPE_NUMBERED_ID = 'POINT_CHANGE_TYPE_NUMBERED_ID';
export const INDENT_CHANGE_TYPE_ACTION_ID = 'INDENT_CHANGE_TYPE_ACTION_ID';
export const INDENT_CHANGE_TYPE_NO_GRAPHIC_ID =
  'INDENT_CHANGE_TYPE_NO_GRAPHIC_ID';
export const INDENT_CHANGE_TYPE_LONG_INDENT_ID =
  'INDENT_CHANGE_TYPE_LONG_INDENT_ID';
export const INDENT_CHANGE_TYPE_NUMBERED_ID = 'INDENT_CHANGE_TYPE_NUMBERED_ID';
export const ARTICLE_TYPE_CHANGE_ACTION_ID = 'ARTICLE_TYPE_CHANGE_ACTION_ID';
export const ARTICLE_TYPE_REGULAR = 'ARTICLE_TYPE_REGULAR';
export const ARTICLE_TYPE_DEFINITION = 'ARTICLE_TYPE_DEFINITION';

export const PART_NUMBER_CHANGE_ID = 'PART_NUMBER_CHANGE_ID';
export const PART_NUMBER_TEXTUTAL = 'PART_NUMBER_TEXTUTAL';
export const PART_NUMBER_ROMAN = 'PART_NUMBER_ROMAN';
export const CHAPTER_NUMBER_CHANGE_ID = 'CHAPTER_NUMBER_CHANGE_ID';
export const CHAPTER_NUMBER_ROMAN = 'CHAPTER_NUMBER_ROMAN';
export const CHAPTER_NUMBER_ARABIC = 'CHAPTER_NUMBER_ARABIC';

export const PLACE_BEFORE_ACTION_ID = 'PLACE_BEFORE_ACTION_ID';
export const PLACE_AS_CHILDREN_ACTION_ID = 'PLACE_AS_CHILDREN_ACTION_ID';
export const PLACE_AFTER_ACTION_ID = 'PLACE_AFTER_ACTION_ID';
export const CANCEL_MOVE_ID = 'CANCEL_MOVE_ID';
