#hibernate config
spring.profiles.active=h2
server.servlet.context-path=/ud-repo

logging.file=user-repository.log
spring.main.banner-mode=off

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator