# This Dockerfile is used to create an image to test-cypress to be used in our runner in gitlab
# The base used image is documented here: https://hub.docker.com/r/cypress/factory/
# From this base image page we have links to updated version numbers of node and chrome
#
# To create the image itself those commands were used:
# docker build -f Dockerfile.tests -t code.europa.eu:4567/leos/core/image-for-tests:1.0.3 . (change version when create a new one)
# docker login code.europa.eu:4567 (with gitlab user and token created in gitlab profile)
# docker push code.europa.eu:4567/leos/core/image-for-tests:1.0.3 (change version when create a new one)
#
# Container Registry page: https://code.europa.eu/leos/core/container_registry
#

ARG NODE_VERSION='20.14.0'
ARG CHROME_VERSION='133.0.6943.126-1'

FROM cypress/factory:latest
ENV JAVA_HOME=/opt/openlogic-openjdk-8u402-b06-linux-x64
ENV M2_HOME=/opt/apache-maven-3.9.6
ENV PATH=${PATH}:/opt/openlogic-openjdk-8u402-b06-linux-x64/bin:/opt/apache-maven-3.9.6/bin

RUN wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u402-b06/openlogic-openjdk-8u402-b06-linux-x64.tar.gz \
    && tar -xvf openlogic-openjdk-8u402-b06-linux-x64.tar.gz \
    && mv openlogic-openjdk-8u402-b06-linux-x64 /opt/
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz \
    && tar -xvf apache-maven-3.9.6-bin.tar.gz \
    && mv apache-maven-3.9.6 /opt/
