SET SERVEROUTPUT ON
SET TIMING ON

CREATE TABLE REPOSITORY
(	ID NUMBER(22,0),
     CMIS_ID VARCHAR2(100 BYTE),
     NAME VARCHAR2(100 BYTE),
     DESCRIPTION VARCHAR2(100 BYTE),
     ALL_VERSIONS_SEARCHABLE NUMBER(1,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

ALTER TABLE REPOSITORY ADD CONSTRAINT REPOSITORY_PK PRIMARY KEY (ID);

ALTER TABLE REPOSITORY MODIFY (ID NOT NULL ENABLE);

ALTER TABLE REPOSITORY MODIFY (CMIS_ID NOT NULL ENABLE);

ALTER TABLE REPOSITORY MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE REPOSITORY MODIFY (DESCRIPTION NOT NULL ENABLE);

ALTER TABLE REPOSITORY ADD CONSTRAINT REPOSITORY_UQ UNIQUE (NAME);

CREATE TABLE PERMISSION
(	ID NUMBER(22,0),
     REPOSITORY_ID NUMBER(22,0),
     NAME VARCHAR2(100 BYTE),
     DESCRIPTION VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

ALTER TABLE PERMISSION ADD CONSTRAINT PERMISSION_PK PRIMARY KEY (ID);

ALTER TABLE PERMISSION MODIFY (ID NOT NULL ENABLE);

ALTER TABLE PERMISSION MODIFY (REPOSITORY_ID NOT NULL ENABLE);

ALTER TABLE PERMISSION MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE PERMISSION MODIFY (DESCRIPTION NOT NULL ENABLE);

ALTER TABLE PERMISSION MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE PERMISSION MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE PERMISSION ADD CONSTRAINT PERMISSION_FK FOREIGN KEY (REPOSITORY_ID)
    REFERENCES REPOSITORY (ID) ENABLE;

CREATE TABLE ACL
(	ID NUMBER(22,0),
     IS_DIRECT NUMBER(1,0),
     OBJECT_ID NUMBER(22,0),
     PERMISSION_ID NUMBER(22,0),
     PRINCIPAL_ID VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
);

ALTER TABLE ACL ADD CONSTRAINT ACL_PK PRIMARY KEY (ID);

ALTER TABLE ACL MODIFY (ID NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (IS_DIRECT NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (OBJECT_ID NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (PERMISSION_ID NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (PRINCIPAL_ID NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE ACL MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

CREATE TABLE CHANGE_EVENT
(	ID NUMBER(22,0),
     REPOSITORY_ID NUMBER(22,0),
     DOCUMENT_ID NUMBER(22,0),
     CHANGE_TYPE VARCHAR2(100 BYTE),
     CHANGE_LOG_TOKEN VARCHAR2(100 BYTE),
     CHANGE_TIME TIMESTAMP (6),
     USERNAME VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE)
) ;

ALTER TABLE CHANGE_EVENT ADD CONSTRAINT CHANGE_EVENT_PK PRIMARY KEY (ID);

ALTER TABLE CHANGE_EVENT MODIFY (ID NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (REPOSITORY_ID NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (DOCUMENT_ID NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_TYPE NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_LOG_TOKEN NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (CHANGE_TIME NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (USERNAME NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE CHANGE_EVENT MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

CREATE TABLE "PACKAGE"
(	ID NUMBER,
     OBJECT_ID NUMBER,
     NAME VARCHAR2(400 BYTE),
     REPOSITORY_ID NUMBER,
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
) ;

ALTER TABLE "PACKAGE" ADD CONSTRAINT PACKAGE_PK PRIMARY KEY (ID);
ALTER TABLE "PACKAGE" ADD CONSTRAINT PACKAGE_UQ UNIQUE (NAME, REPOSITORY_ID);

CREATE TABLE DOCUMENT_CATEGORIES
(	ID NUMBER,
     CATEGORY_CODE VARCHAR2(30 BYTE),
     CATEGORY_DESC VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

ALTER TABLE DOCUMENT_CATEGORIES ADD CONSTRAINT DOCUMENT_CATEGORIES_CHK_UQ UNIQUE (CATEGORY_CODE);

ALTER TABLE DOCUMENT_CATEGORIES ADD CONSTRAINT DOCUMENT_CATEGORIES_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (CATEGORY_CODE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (CATEGORY_DESC NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CATEGORIES MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

CREATE TABLE DOCUMENT_MILESTONE
(	ID NUMBER,
     DOCUMENT_ID NUMBER,
     JOB_DATE DATE,
     MILESTONE_COMMENTS VARCHAR2(4000 BYTE),
     CONTENT BLOB,
     STATUS VARCHAR2(30 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     JOB_ID VARCHAR2(400 BYTE),
     EXPORT_STATUS VARCHAR2(30 BYTE),
     EXPORT_DATE TIMESTAMP (6)
)
    PARTITION BY RANGE (JOB_DATE) INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(PARTITION DOC_MILESTONE_PART_DEF  VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
) ;

ALTER TABLE DOCUMENT_MILESTONE ADD CONSTRAINT DOCUMENT_MILESTONE_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (JOB_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (DOCUMENT_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (JOB_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (STATUS NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

/*
CREATE TABLE DOCUMENT_MILESTONE_COMMENTS
(	ID NUMBER,
     MILESTONE_ID NUMBER,
     COMMENTS VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
) ;

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (MILESTONE_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_COMMENTS MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

CREATE INDEX DOC_MIL_COMMENTS_MIL_IDX ON DOCUMENT_MILESTONE_COMMENTS (MILESTONE_ID);
*/

CREATE TABLE DOCUMENT_MILESTONE_LIST
(	ID NUMBER,
     MILESTONE_ID NUMBER,
     CONTAINED_DOCUMENTS VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
);

ALTER TABLE DOCUMENT_MILESTONE_LIST ADD CONSTRAINT DOCUMENT_MILESTONE_LIST_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (MILESTONE_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (CONTAINED_DOCUMENTS NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_LIST MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_MILESTONE_LIST ADD CONSTRAINT DOCUMENT_MILESTONE_LIST_FK FOREIGN KEY (MILESTONE_ID)
    REFERENCES DOCUMENT_MILESTONE (ID) ENABLE;

CREATE TABLE DOCUMENT_VERSION
(	ID NUMBER,
     DOCUMENT_ID NUMBER,
     VERSION_LABEL VARCHAR2(100 BYTE),
     VERSION_SERIES_ID VARCHAR2(400 BYTE),
     VERSION_TYPE VARCHAR2(100 BYTE),
     IS_LATEST_MAJOR_VERSION NUMBER(*,0),
     IS_LATEST_VERSION NUMBER(*,0),
     IS_MAJOR_VERSION NUMBER(*,0),
     IS_VERSION_SERIES_CHECKED_OUT NUMBER(*,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     IS_IMMUTABLE NUMBER,
     COMMENTS VARCHAR2(4000)
);

ALTER TABLE DOCUMENT_VERSION ADD CONSTRAINT DOCUMENT_VERSIONS_PK PRIMARY KEY (ID);
ALTER TABLE DOCUMENT_VERSION ADD CONSTRAINT DOCUMENT_VERSION_UQ UNIQUE (DOCUMENT_ID, VERSION_LABEL);

CREATE TABLE DOCUMENT_PROPERTIES
(	ID NUMBER,
     PROPERTY_NAME VARCHAR2(30 BYTE),
     DOC_CATEGORY_ID NUMBER,
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6)
) ;

ALTER TABLE DOCUMENT_PROPERTIES ADD CONSTRAINT DOCUMENT_PROPERTIES_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_PROPERTIES ADD CONSTRAINT DOCUMENT_PROPERTIES_FK2 FOREIGN KEY (DOC_CATEGORY_ID)
    REFERENCES DOCUMENT_CATEGORIES (ID) ENABLE;

ALTER TABLE DOCUMENT_PROPERTIES ADD CONSTRAINT DOCUMENT_PROPERTIES_UQ UNIQUE (PROPERTY_NAME, DOC_CATEGORY_ID);

CREATE TABLE DOCUMENT_PROPERTY_VALUES
(	ID NUMBER,
     DOCUMENT_ID NUMBER,
     PROPERTY_ID NUMBER,
     PROPERTY_VALUE VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     VERSION_ID NUMBER
) ;

ALTER TABLE DOCUMENT_PROPERTY_VALUES ADD CONSTRAINT DOCUMENT_PROPERTY_VALUES_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_PROPERTY_VALUES ADD CONSTRAINT DOCUMENT_PROPERTY_VALUES_FK2 FOREIGN KEY (PROPERTY_ID)
    REFERENCES DOCUMENT_PROPERTIES (ID) ENABLE;

ALTER TABLE DOCUMENT_PROPERTY_VALUES ADD CONSTRAINT DOC_PROPERTY_VAL_FK FOREIGN KEY (VERSION_ID)
    REFERENCES DOCUMENT_VERSION (ID) ENABLE;


CREATE TABLE DOCUMENT
(	ID NUMBER(22,0),
     OBJECT_ID NUMBER,
     PACKAGE_ID NUMBER(22,0),
     CATEGORY_ID NUMBER(22,0),
     NAME VARCHAR2(400 BYTE),
     CLONED_FROM VARCHAR2(400 BYTE),
     REVISION_STATUS VARCHAR2(30 BYTE),
     CONTRIBUTION_STATUS VARCHAR2(30 BYTE),
     ORIGIN_REF VARCHAR2(30 BYTE),
     BASE_REVISION_ID NUMBER(22,0),
     LIVE_DIFFING_REQUIRED NUMBER(*,0),
     REF VARCHAR2(400 BYTE),
     PROCEDURE_TYPE VARCHAR2(100 BYTE),
     DOC_TEMPLATE VARCHAR2(400 BYTE),
     LANGUAGE VARCHAR2(10 BYTE),
     DOC_STAGE VARCHAR2(400 BYTE),
     IS_PRIVATE_WORKING_COPY NUMBER(*,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     IS_ARCHIVED NUMBER(*,0)
);

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_FK FOREIGN KEY (PACKAGE_ID)
    REFERENCES "PACKAGE" (ID) ENABLE;

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_METADATA_FK3 FOREIGN KEY (CATEGORY_ID)
    REFERENCES DOCUMENT_CATEGORIES (ID) ENABLE;

ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_UQ UNIQUE (REF, NAME);

CREATE TABLE DOCUMENT_CONTENT
(	"ID" NUMBER,
     "VERSION_ID" NUMBER,
     "CATEGORY_CODE" VARCHAR2(100),
     "CONTENT" CLOB,
     "ACT_TYPE" VARCHAR2(100),
     "DOC_PURPOSE" VARCHAR2(400),
     "DOC_TYPE" VARCHAR2(400),
     "EEA_RELEVANCE" NUMBER(*,0),
     "TEMPLATE" VARCHAR2(400),
     "TITLE" VARCHAR2(400),
     "AUDIT_C_BY" VARCHAR2(30),
     "AUDIT_C_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     "AUDIT_LAST_M_BY" VARCHAR2(30),
     "AUDIT_LAST_M_DATE" TIMESTAMP (6)
)   PARTITION BY RANGE ("AUDIT_C_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
    SUBPARTITION BY LIST ("CATEGORY_CODE")
    SUBPARTITION TEMPLATE (
                              SUBPARTITION "DOC_XML_SUB_ANN" VALUES ( 'ANNEX' ),
                              SUBPARTITION "DOC_XML_SUB_BIL" VALUES ( 'BILL' ),
                              SUBPARTITION "DOC_XML_SUB_COU" VALUES ( 'COUNCIL_EXPLANATORY' ),
                              SUBPARTITION "DOC_XML_SUB_EXP" VALUES ( 'EXPORT' ),
                              SUBPARTITION "DOC_XML_SUB_FIN" VALUES ( 'FINANCIAL_STATEMENT' ),
                              SUBPARTITION "DOC_XML_SUB_LEG" VALUES ( 'LEG' ),
                              SUBPARTITION "DOC_XML_SUB_MEM" VALUES ( 'MEMORANDUM' ),
                              SUBPARTITION "DOC_XML_SUB_PRO" VALUES ( 'PROPOSAL' ),
                              SUBPARTITION "DOC_XML_SUB_STA" VALUES ( 'STAT_FINANC_LEGIS' ),
                              SUBPARTITION "DOC_XML_SUB_DEFAULT" VALUES ( DEFAULT ) )
(PARTITION "DOC_XML_PART_DEF"  VALUES LESS THAN (TIMESTAMP' 2020-01-01 00:00:00'));

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_PK PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_CAT_FK FOREIGN KEY (CATEGORY_CODE)
    REFERENCES DOCUMENT_CATEGORIES (CATEGORY_CODE) ENABLE;

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_FK FOREIGN KEY (VERSION_ID)
    REFERENCES DOCUMENT_VERSION (ID) ENABLE;

ALTER TABLE DOCUMENT_CONTENT ADD CONSTRAINT DOCUMENT_CONTENT_UQ UNIQUE (VERSION_ID);

CREATE TABLE CONFIG_CATEGORIES
(	ID NUMBER,
     CATEGORY_CODE VARCHAR2(30 BYTE),
     CATEGORY_DESC VARCHAR2(100 BYTE),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     CATEGORY_TYPE VARCHAR2(40 BYTE)
);

ALTER TABLE CONFIG_CATEGORIES ADD CONSTRAINT CONFIG_CATEGORIES_PK PRIMARY KEY (ID);
ALTER TABLE CONFIG_CATEGORIES ADD CONSTRAINT CONFIG_CATEGORIES_UQ UNIQUE (CATEGORY_CODE);

CREATE TABLE CONFIG_VERSION
(	ID NUMBER,
     CONFIG_ID NUMBER,
     VERSION_LABEL VARCHAR2(100 BYTE),
     VERSION_SERIES_ID VARCHAR2(400 BYTE),
     VERSION_TYPE VARCHAR2(100 BYTE),
     IS_LATEST_MAJOR_VERSION NUMBER(*,0),
     IS_LATEST_VERSION NUMBER(*,0),
     IS_MAJOR_VERSION NUMBER(*,0),
     IS_VERSION_SERIES_CHECKED_OUT NUMBER(*,0),
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSDATE,
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     IS_IMMUTABLE NUMBER(1,0)
);

ALTER TABLE CONFIG_VERSION ADD CONSTRAINT CONFIG_VERSIONS_PK PRIMARY KEY (ID);
ALTER TABLE CONFIG_VERSION ADD CONSTRAINT CONFIG_VERSION_UQ UNIQUE (CONFIG_ID, VERSION_LABEL);

CREATE TABLE CONFIG_CONTENT
(	VERSION_ID NUMBER,
     CONTENT BLOB,
     CONTENT_STREAM_MIME_TYPE VARCHAR2(4000 BYTE),
     CONTENT_STREAM_FILENAME VARCHAR2(4000 BYTE),
     CONTENT_STREAM_ID VARCHAR2(4000 BYTE),
     CONTENT_STREAM_LENGTH VARCHAR2(4000 BYTE),
     AUDIT_C_BY VARCHAR2(4000 BYTE),
     AUDIT_C_DATE TIMESTAMP (9),
     AUDIT_LAST_M_DATE TIMESTAMP (9),
     AUDIT_LAST_M_BY VARCHAR2(4000 BYTE),
     ID NUMBER
);
ALTER TABLE CONFIG_CONTENT ADD CONSTRAINT CONTENT_PK PRIMARY KEY (ID);

ALTER TABLE CONFIG_CONTENT ADD CONSTRAINT CONFIGURATION_CONTENT_FK FOREIGN KEY (VERSION_ID)
    REFERENCES CONFIG_VERSION (ID) ENABLE;

ALTER TABLE CONFIG_CONTENT ADD CONSTRAINT CONFIG_CONTENT_UQ UNIQUE (VERSION_ID);

CREATE TABLE CONFIG
(	ID NUMBER,
     NAME VARCHAR2(100 BYTE),
     OBJECT_ID NUMBER,
     CATEGORY_ID NUMBER,
     AUDIT_C_BY VARCHAR2(30 BYTE),
     AUDIT_C_DATE TIMESTAMP (6),
     AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
     AUDIT_LAST_M_DATE TIMESTAMP (6),
     ORIGINAL_ID NUMBER,
     REPOSITORY_ID NUMBER,
     LANGUAGE VARCHAR2(10 BYTE)
);

ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_PK PRIMARY KEY (ID);
ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CONFIG_CATEGORIES (ID);
ALTER TABLE CONFIG ADD CONSTRAINT CONFIG_UQ UNIQUE (NAME, REPOSITORY_ID);

CREATE TABLE COLLABORATORS
(
    ID NUMBER,
    COLLABORATOR_NAME VARCHAR2(100) NOT NULL,
    ROLE_ID VARCHAR2(100) NOT NULL,
    ORGANIZATION VARCHAR2(100) NOT NULL,
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    CONSTRAINT COLLABORATORS_PK PRIMARY KEY (ID)
);

ALTER TABLE COLLABORATORS ADD CONSTRAINT COLLABORATORS_UQ UNIQUE (COLLABORATOR_NAME, ROLE_ID);

CREATE TABLE PACKAGE_COLLABORATORS
(
    ID NUMBER,
    PACKAGE_ID NUMBER,
    COLLABORATOR_ID NUMBER NOT NULL,
    AUDIT_C_BY VARCHAR2(30 BYTE),
    AUDIT_C_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    AUDIT_LAST_M_DATE TIMESTAMP (6),
    AUDIT_LAST_M_BY VARCHAR2(30 BYTE),
    CONSTRAINT PACKAGE_COLLABORATORS_PK PRIMARY KEY (ID),
    CONSTRAINT PACKAGE_COLLABORATORS_FK FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE (ID),
    CONSTRAINT PACKAGE_COLLABORATORS_FK2 FOREIGN KEY (COLLABORATOR_ID) REFERENCES COLLABORATORS (ID)
);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (PROPERTY_NAME NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (DOC_CATEGORY_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTIES MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (DOCUMENT_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (PROPERTY_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_PROPERTY_VALUES MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (ID NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (OBJECT_ID NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (REPOSITORY_ID NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE "PACKAGE" MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE CONFIG_CONTENT MODIFY (VERSION_ID NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (ID NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (CONFIG_ID NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (VERSION_SERIES_ID NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (IS_LATEST_MAJOR_VERSION NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (IS_LATEST_VERSION NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (IS_MAJOR_VERSION NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (IS_VERSION_SERIES_CHECKED_OUT NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE CONFIG_VERSION MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (VERSION_SERIES_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_LATEST_MAJOR_VERSION NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_LATEST_VERSION NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_MAJOR_VERSION NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (IS_VERSION_SERIES_CHECKED_OUT NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_VERSION MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE CONFIG_CATEGORIES MODIFY (ID NOT NULL ENABLE);

ALTER TABLE CONFIG_CATEGORIES MODIFY (CATEGORY_CODE NOT NULL ENABLE);

ALTER TABLE CONFIG_CATEGORIES MODIFY (CATEGORY_DESC NOT NULL ENABLE);

ALTER TABLE CONFIG_CATEGORIES MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE CONFIG_CATEGORIES MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE CONFIG MODIFY (ID NOT NULL ENABLE);

ALTER TABLE CONFIG MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE CONFIG MODIFY (OBJECT_ID NOT NULL ENABLE);

ALTER TABLE CONFIG MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE CONFIG MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (PACKAGE_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (CATEGORY_ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (REF NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (DOC_TEMPLATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (LANGUAGE NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (DOC_STAGE NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (DOC_PURPOSE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (DOC_TYPE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (TEMPLATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (TITLE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (AUDIT_C_BY NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (AUDIT_C_DATE NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (CONTENT NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (ID NOT NULL ENABLE);

ALTER TABLE DOCUMENT_CONTENT MODIFY (VERSION_ID NOT NULL ENABLE);

CREATE INDEX DOC_MILESTONE_DOC_IDX ON DOCUMENT_MILESTONE (DOCUMENT_ID);

CREATE INDEX DOC_MIL_LIST_MIL_IDX ON DOCUMENT_MILESTONE_LIST (MILESTONE_ID);

CREATE INDEX DOC_VERSIONS_LMV_IDX ON DOCUMENT_VERSION (IS_LATEST_MAJOR_VERSION);

CREATE INDEX DOC_VERSIONS_LAV_IDX ON DOCUMENT_VERSION (IS_LATEST_VERSION);

CREATE INDEX DOC_VERSIONS_MAV_IDX ON DOCUMENT_VERSION (IS_MAJOR_VERSION);

CREATE INDEX DOC_VERSIONS_VCO_IDX ON DOCUMENT_VERSION (IS_VERSION_SERIES_CHECKED_OUT);

CREATE INDEX DOC_PRO_CAT_IDX ON DOCUMENT_PROPERTIES (DOC_CATEGORY_ID);

CREATE INDEX DOC_PROVAL_DOC_IDX ON DOCUMENT_PROPERTY_VALUES (DOCUMENT_ID);

CREATE INDEX DOC_PROVAL_PRO_IDX ON DOCUMENT_PROPERTY_VALUES (PROPERTY_ID);

CREATE INDEX PACKAGE_COLLABORATORS_IDX ON PACKAGE_COLLABORATORS (PACKAGE_ID);

CREATE INDEX PACKAGE_COLLABORATORS_IDX2 ON PACKAGE_COLLABORATORS (COLLABORATOR_ID);

CREATE OR REPLACE FORCE EDITIONABLE VIEW DOCUMENT_V  AS
SELECT doc.id||'_'||docver.id||'_'||docxml.id||'_'||doccat.id unique_id
     , doc.id document_id,doc.object_id doc_object_id,doc.category_id
     , doc.package_id, docxml.version_id
     , doccat.category_code, doccat.category_desc
     , doc.name,doc.cloned_from,doc.revision_status,doc.contribution_status,doc.origin_ref,doc.base_revision_id,doc.live_diffing_required,doc.ref,doc.procedure_type,doc.doc_template,doc.language,doc.doc_stage,doc.is_private_working_copy
     , docver.audit_c_by doc_audit_c_by,docver.audit_c_date doc_audit_c_date,docver.audit_last_m_date doc_audit_last_m_date,docver.audit_last_m_by doc_audit_last_m_by
     , docver.version_label, docver.version_series_id, docver.version_type, docver.is_latest_major_version, docver.is_latest_version, docver.is_major_version, docver.is_version_series_checked_out
     , docxml.act_type, docxml.doc_purpose, docxml.doc_type, docxml.eea_relevance, docxml.template, docxml.title, docver.comments, doc.is_archived
FROM document doc, document_version docver, document_content docxml, document_categories_v doccat
WHERE doc.id = docver.document_id
  AND docver.id = docxml.version_id
  AND doc.category_id = doccat.id;

CREATE OR REPLACE FORCE EDITIONABLE VIEW DOCUMENT_CATEGORIES_V (ID, CATEGORY_CODE, CATEGORY_DESC, AUDIT_C_BY, AUDIT_C_DATE, AUDIT_LAST_M_BY, AUDIT_LAST_M_DATE) AS
SELECT ID,CATEGORY_CODE,CATEGORY_DESC,AUDIT_C_BY,AUDIT_C_DATE,AUDIT_LAST_M_BY,AUDIT_LAST_M_DATE FROM DOCUMENT_CATEGORIES;

CREATE OR REPLACE FORCE EDITIONABLE VIEW MILESTONE_V as
SELECT doc.id||'_'||docmil.id unique_id, doc.id document_id, doc.package_id, doc.object_id doc_object_id,doc.category_id,doc.name,doc.cloned_from,doc.revision_status,doc.contribution_status,doc.origin_ref,doc.base_revision_id,doc.live_diffing_required,doc.ref,doc.procedure_type,doc.doc_template,doc.language,doc.doc_stage,doc.is_private_working_copy,doc.audit_c_by doc_audit_c_by,doc.audit_c_date doc_audit_c_date,doc.audit_last_m_date doc_audit_last_m_date,doc.audit_last_m_by doc_audit_last_m_by
        , docmil.id milestone_id, docmil.job_id, docmil.job_date, docmil.export_date, docmil.export_status, docmil.milestone_comments,
       docmil.content, docmil.status, docmil.audit_c_by, docmil.audit_c_date, docmil.audit_last_m_date, docmil.audit_last_m_by
FROM document doc, document_milestone docmil
WHERE doc.id = docmil.document_id;

CREATE OR REPLACE FORCE EDITIONABLE VIEW MILESTONE_LIST_V as
SELECT milv.milestone_id||'_'||millis.id unique_id, milv.package_id, milv.document_id, milv.milestone_id
     , millis.contained_documents, millis.audit_c_by, millis.audit_c_date, millis.audit_last_m_date, millis.audit_last_m_by
FROM milestone_v milv, document_milestone_list millis
WHERE milv.milestone_id = millis.milestone_id;

CREATE OR REPLACE FORCE EDITIONABLE VIEW CONFIGURATION_V as
SELECT conf.id||'_'||ver.id||'_'||con.id||'_'||cat.id unique_id, conf.ID, CONF.NAME, CONF.OBJECT_ID,
       ver.config_id,cat.category_code, cat.category_desc, ver.version_label,ver.version_series_id,ver.version_type,ver.is_latest_major_version,ver.is_latest_version,ver.is_major_version,ver.is_version_series_checked_out,ver.audit_c_by,ver.audit_c_date,ver.audit_last_m_by,ver.audit_last_m_date,ver.is_immutable
        , con.content,con.content_stream_mime_type,con.content_stream_filename,con.content_stream_id,con.content_stream_length
FROM config conf, config_version ver, config_content con, config_categories cat
WHERE
        conf.id = ver.config_id
  and ver.id = con.version_id
  AND conf.CATEGORY_ID = cat.ID;

CREATE OR REPLACE FORCE EDITIONABLE VIEW PACKAGE_V AS
SELECT pkg.id||'_'||doc.id||'_'||docver.id||'_'||docxml.id unique_id, pkg.id package_id, pkg.object_id pkg_object_id, pkg.name package_name, pkg.repository_id, pkg.audit_c_date, pkg.audit_c_by, pkg.audit_last_m_date, pkg.audit_last_m_by
     , doc.id document_id,doc.object_id doc_object_id,doc.category_id,doc.name,doc.cloned_from,doc.revision_status,doc.contribution_status,doc.origin_ref,doc.base_revision_id,doc.live_diffing_required,doc.ref,doc.procedure_type,doc.doc_template,doc.language,doc.doc_stage,doc.is_private_working_copy,doc.audit_c_by doc_audit_c_by,doc.audit_c_date doc_audit_c_date,doc.audit_last_m_date doc_audit_last_m_date,doc.audit_last_m_by doc_audit_last_m_by
     , docver.version_label, docver.version_series_id, docver.version_type, docver.is_latest_major_version, docver.is_latest_version, docver.is_major_version, docver.is_version_series_checked_out
     , docxml.content, docxml.act_type, docxml.doc_purpose, docxml.doc_type, docxml.eea_relevance, docxml.template, docxml.title
FROM PACKAGE pkg, document doc, document_version docver, document_content docxml
WHERE pkg.id = doc.package_id
  and doc.id = docver.document_id
  AND docver.id = docxml.version_id;

CREATE OR REPLACE FORCE EDITIONABLE VIEW DOCUMENT_PROPERTIES_V as
SELECT doc.id||'_'||cat.id||'_'||docver.id||'_'||pro.id||'_'||proval.id unique_id, doc.id,doc.object_id,doc.package_id,doc.category_id,cat.category_code,cat.category_desc,doc.name
     , proval.version_id, docver.version_label,docver.version_series_id,docver.version_type
     , pro.id prop_id,pro.property_name
     , proval.id prop_value_id,proval.property_value,proval.audit_c_by,proval.audit_c_date,proval.audit_last_m_by,proval.audit_last_m_date
FROM document doc, document_categories cat, document_version docver, document_properties pro, document_property_values proval
WHERE doc.category_id = cat.id
  AND cat.id = pro.doc_category_id
  AND doc.id = proval.document_id
  AND pro.id = proval.property_id
  AND proval.version_id = docver.id
  AND doc.id = docver.document_id;


CREATE SEQUENCE  ACL_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  CHANGE_EVENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  CONFIG_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_CATEGORIES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_VERSIONS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 40001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_CONTENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  PERMISSION_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  PACKAGE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE OR REPLACE EDITIONABLE TRIGGER PROPOSAL_TRG
    BEFORE INSERT ON "PACKAGE"
    for each row
begin
    :new.id := proposal_seq.nextval;
end;

/
ALTER TRIGGER PROPOSAL_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_VERSIONS_TRG
    BEFORE INSERT ON DOCUMENT_VERSION
    for each row
begin
    :new.id := document_versions_seq.nextval;
end;

/
ALTER TRIGGER DOCUMENT_VERSIONS_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER ACL_TRG
    BEFORE INSERT ON acl
    for each row
begin
    :new.id := acl_seq.nextval;
end;

/
ALTER TRIGGER ACL_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER PERMISSION_TRG
    BEFORE INSERT ON permission
    for each row
begin
    :new.id := permission_seq.nextval;
end;

/
ALTER TRIGGER PERMISSION_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER CHANGE_EVENT_TRG
    BEFORE INSERT ON change_event
    for each row
begin
    :new.id := change_event_seq.nextval;
end;

/
ALTER TRIGGER CHANGE_EVENT_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER CONFIG_TRG
    BEFORE INSERT ON CONFIG
    for each row
begin
    :new.id := config_seq.nextval;
end;

/
ALTER TRIGGER CONFIG_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_CATEGORIES_TRG
    BEFORE INSERT ON document_categories
    for each row
begin
    :new.id := document_categories_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_CATEGORIES_TRG ENABLE;

CREATE SEQUENCE  REPOSITORY_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_MILESTONE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_MILESTONE_COMMENTS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_MILESTONE_LIST_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_PROPERTIES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  DOCUMENT_PROPERTY_VALUES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  CONFIG_CONTENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  CONFIG_VERSION_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  CONFIG_CATEGORIES_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  COLLABORATORS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  PACKAGE_COLLABORATORS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE OR REPLACE EDITIONABLE TRIGGER REPOSITORY_TRG
    BEFORE INSERT ON REPOSITORY
    for each row
begin
    :new.id := repository_seq.nextval;
end;
/

ALTER TRIGGER REPOSITORY_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER PERMISSION_TRG
    BEFORE INSERT ON PERMISSION
    for each row
begin
    :new.id := permission_seq.nextval;
end;
/

ALTER TRIGGER PERMISSION_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER ACL_TRG
    BEFORE INSERT ON acl
    for each row
begin
    :new.id := acl_seq.nextval;
end;
/

ALTER TRIGGER ACL_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER CHANGE_EVENT_TRG
    BEFORE INSERT ON change_event
    for each row
begin
    :new.id := change_event_seq.nextval;
end;
/

ALTER TRIGGER CHANGE_EVENT_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_CATEGORIES_TRG
    BEFORE INSERT ON DOCUMENT_CATEGORIES
    for each row
begin
    :new.id := document_categories_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_CATEGORIES_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_MILESTONE_TRG
    BEFORE INSERT ON DOCUMENT_MILESTONE
    for each row
begin
    :new.id := document_milestone_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_MILESTONE_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_MILESTONE_LIST_TRG
    BEFORE INSERT ON DOCUMENT_MILESTONE_LIST
    for each row
begin
    :new.id := document_milestone_list_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_MILESTONE_LIST_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_PROPERTIES_TRG
    BEFORE INSERT ON DOCUMENT_PROPERTIES
    for each row
begin
    :new.id := document_properties_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_PROPERTIES_TRG ENABLE;



CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_PROPERTY_VALUES_TRG
    BEFORE INSERT ON DOCUMENT_PROPERTY_VALUES
    for each row
begin
    :new.id := document_property_values_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_PROPERTY_VALUES_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER PACKAGE_TRG
    BEFORE INSERT ON "PACKAGE"
    for each row
begin
    :new.id := PACKAGE_seq.nextval;
end;
/

ALTER TRIGGER PACKAGE_TRG ENABLE;


CREATE OR REPLACE EDITIONABLE TRIGGER CONFIG_CONTENT_TRG
    BEFORE INSERT ON CONFIG_CONTENT
    for each row
begin
    :new.id := config_content_seq.nextval;
end;
/

ALTER TRIGGER CONFIG_CONTENT_TRG ENABLE;



CREATE OR REPLACE EDITIONABLE TRIGGER CONFIG_VERSION_TRG
    BEFORE INSERT ON CONFIG_VERSION
    for each row
begin
    :new.id := config_version_seq.nextval;
end;
/

ALTER TRIGGER CONFIG_VERSION_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_VERSIONS_TRG
    BEFORE INSERT ON DOCUMENT_VERSION
    for each row
begin
    :new.id := document_versions_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_VERSIONS_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER CONFIG_CATEGORIES_TRG
    BEFORE INSERT ON CONFIG_CATEGORIES
    for each row
begin
    :new.id := CONFIG_CATEGORIES_seq.nextval;
end;
/

ALTER TRIGGER CONFIG_CATEGORIES_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_TRG
    BEFORE INSERT ON DOCUMENT
    for each row
begin
    :new.id := document_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_CONTENT_TRG
    BEFORE INSERT ON DOCUMENT_CONTENT
    for each row
begin
    :new.id := document_content_seq.nextval;
end;
/

ALTER TRIGGER DOCUMENT_CONTENT_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER DOCUMENT_CATEGORIES_TRG
    BEFORE INSERT ON document_categories
    for each row
begin
    :new.id := document_categories_seq.nextval;
END;
/

ALTER TRIGGER DOCUMENT_CATEGORIES_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER COLLABORATORS_TRG
    BEFORE INSERT ON collaborators
    for each row
begin
    :new.id := collaborators_seq.nextval;
end;
/

ALTER TRIGGER COLLABORATORS_TRG ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER PACKAGE_COLLABORATORS_TRG
    BEFORE INSERT ON package_collaborators
    for each row
begin
    :new.id := package_collaborators_seq.nextval;
end;
/

ALTER TRIGGER PACKAGE_COLLABORATORS_TRG ENABLE;

COMMENT ON TABLE CONFIGURATION_V IS 'View to see all configuration data metadata and content';
COMMENT ON TABLE DOCUMENT_CATEGORIES_V IS 'View to see the categories a document can have';
COMMENT ON TABLE DOCUMENT_PROPERTIES_V IS 'View we can see extra properties for a document, flags like annex number';
COMMENT ON TABLE DOCUMENT_V IS 'View centralizing all documents';
COMMENT ON TABLE MILESTONE_LIST_V IS 'View to see all list of containted documents in a milestone';
COMMENT ON TABLE MILESTONE_V IS 'View about all milestones and exports';
COMMENT ON TABLE PACKAGE_V IS 'View centralizing all packages';
COMMENT ON TABLE ACL IS 'Access control list for LEOS';
COMMENT ON TABLE CHANGE_EVENT IS 'Table for logging the operations at proposal level';
COMMENT ON TABLE CONFIG IS 'Master table for configuration: structure, config, templates';
COMMENT ON TABLE CONFIG_CATEGORIES IS 'The categories a config can have: structure, config, template';
COMMENT ON TABLE CONFIG_CONTENT IS 'The actual content for config, all stored in blob';
COMMENT ON TABLE CONFIG_VERSION IS 'Versions a config can have';
COMMENT ON TABLE DOCUMENT IS 'The header table for documents, all metadata stored here';
COMMENT ON TABLE DOCUMENT_CATEGORIES IS 'Categories for a XML document: ANNEX, BILL, MEMORANDUM etc.';
COMMENT ON TABLE DOCUMENT_CONTENT IS 'The actual table content for Documents, stored in content xmltype';
COMMENT ON TABLE DOCUMENT_MILESTONE IS 'Contents of a milestone or export, zip format in column content';
COMMENT ON TABLE DOCUMENT_MILESTONE_LIST IS 'Documents included in a milestone';
COMMENT ON TABLE DOCUMENT_PROPERTIES IS 'Catalog with the properties that an xml document can have: number, title etc.';
COMMENT ON TABLE DOCUMENT_PROPERTY_VALUES IS 'The actual values for the properties of a document';
COMMENT ON TABLE DOCUMENT_VERSION IS 'An xml file can have multiple versions, minor or major versions.';
COMMENT ON TABLE "PACKAGE" IS 'This is a package or proposal and it contains all documents';
COMMENT ON TABLE PERMISSION IS 'The permissions for repository.';
COMMENT ON TABLE REPOSITORY IS 'The repository for LEOS.';
COMMENT ON COLUMN ACL.ID IS 'Technical ID';
COMMENT ON COLUMN ACL.IS_DIRECT IS '';
COMMENT ON COLUMN ACL.OBJECT_ID IS '';
COMMENT ON COLUMN ACL.PERMISSION_ID IS '';
COMMENT ON COLUMN ACL.PRINCIPAL_ID IS '';
COMMENT ON COLUMN ACL.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN ACL.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN ACL.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN ACL.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIG.ID IS '';
COMMENT ON COLUMN CONFIG.NAME IS '';
COMMENT ON COLUMN CONFIG.OBJECT_ID IS '';
COMMENT ON COLUMN CONFIG.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN CONFIG.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN CONFIG.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIG.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN CONFIG.LANGUAGE IS '';
COMMENT ON COLUMN CONFIG.REPOSITORY_ID IS '';
COMMENT ON COLUMN CONFIG.ORIGINAL_ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.NAME IS '';
COMMENT ON COLUMN CONFIGURATION_V.OBJECT_ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONFIG_ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.CATEGORY_CODE IS '';
COMMENT ON COLUMN CONFIGURATION_V.CATEGORY_DESC IS '';
COMMENT ON COLUMN CONFIGURATION_V.VERSION_LABEL IS '';
COMMENT ON COLUMN CONFIGURATION_V.VERSION_SERIES_ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.VERSION_TYPE IS '';
COMMENT ON COLUMN CONFIGURATION_V.IS_LATEST_MAJOR_VERSION IS '';
COMMENT ON COLUMN CONFIGURATION_V.IS_LATEST_VERSION IS '';
COMMENT ON COLUMN CONFIGURATION_V.IS_MAJOR_VERSION IS '';
COMMENT ON COLUMN CONFIGURATION_V.IS_VERSION_SERIES_CHECKED_OUT IS '';
COMMENT ON COLUMN CONFIGURATION_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN CONFIGURATION_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN CONFIGURATION_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIGURATION_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN CONFIGURATION_V.IS_IMMUTABLE IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONTENT IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONTENT_STREAM_MIME_TYPE IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONTENT_STREAM_FILENAME IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONTENT_STREAM_ID IS '';
COMMENT ON COLUMN CONFIGURATION_V.CONTENT_STREAM_LENGTH IS '';
COMMENT ON COLUMN CONFIG_CATEGORIES.ID IS '';
COMMENT ON COLUMN CONFIG_CATEGORIES.CATEGORY_CODE IS '';
COMMENT ON COLUMN CONFIG_CATEGORIES.CATEGORY_DESC IS '';
COMMENT ON COLUMN CONFIG_CATEGORIES.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN CONFIG_CATEGORIES.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN CONFIG_CATEGORIES.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIG_CATEGORIES.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN CONFIG_CATEGORIES.CATEGORY_TYPE IS '';
COMMENT ON COLUMN CONFIG_CONTENT.ID IS '';
COMMENT ON COLUMN CONFIG_CONTENT.VERSION_ID IS '';
COMMENT ON COLUMN CONFIG_CONTENT.CONTENT IS '';
COMMENT ON COLUMN CONFIG_CONTENT.CONTENT_STREAM_MIME_TYPE IS '';
COMMENT ON COLUMN CONFIG_CONTENT.CONTENT_STREAM_FILENAME IS '';
COMMENT ON COLUMN CONFIG_CONTENT.CONTENT_STREAM_ID IS '';
COMMENT ON COLUMN CONFIG_CONTENT.CONTENT_STREAM_LENGTH IS '';
COMMENT ON COLUMN CONFIG_CONTENT.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN CONFIG_CONTENT.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN CONFIG_CONTENT.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN CONFIG_CONTENT.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIG_VERSION.ID IS '';
COMMENT ON COLUMN CONFIG_VERSION.CONFIG_ID IS '';
COMMENT ON COLUMN CONFIG_VERSION.VERSION_LABEL IS '';
COMMENT ON COLUMN CONFIG_VERSION.VERSION_SERIES_ID IS '';
COMMENT ON COLUMN CONFIG_VERSION.VERSION_TYPE IS '';
COMMENT ON COLUMN CONFIG_VERSION.IS_LATEST_MAJOR_VERSION IS '';
COMMENT ON COLUMN CONFIG_VERSION.IS_LATEST_VERSION IS '';
COMMENT ON COLUMN CONFIG_VERSION.IS_MAJOR_VERSION IS '';
COMMENT ON COLUMN CONFIG_VERSION.IS_VERSION_SERIES_CHECKED_OUT IS '';
COMMENT ON COLUMN CONFIG_VERSION.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN CONFIG_VERSION.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN CONFIG_VERSION.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN CONFIG_VERSION.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN CONFIG_VERSION.IS_IMMUTABLE IS '';
COMMENT ON COLUMN DOCUMENT.IS_PRIVATE_WORKING_COPY IS '';
COMMENT ON COLUMN DOCUMENT.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT.ID IS '';
COMMENT ON COLUMN DOCUMENT.OBJECT_ID IS '';
COMMENT ON COLUMN DOCUMENT.PACKAGE_ID IS '';
COMMENT ON COLUMN DOCUMENT.CATEGORY_ID IS '';
COMMENT ON COLUMN DOCUMENT.NAME IS '';
COMMENT ON COLUMN DOCUMENT.CLONED_FROM IS '';
COMMENT ON COLUMN DOCUMENT.REVISION_STATUS IS '';
COMMENT ON COLUMN DOCUMENT.CONTRIBUTION_STATUS IS '';
COMMENT ON COLUMN DOCUMENT.ORIGIN_REF IS '';
COMMENT ON COLUMN DOCUMENT.BASE_REVISION_ID IS '';
COMMENT ON COLUMN DOCUMENT.LIVE_DIFFING_REQUIRED IS '';
COMMENT ON COLUMN DOCUMENT.REF IS '';
COMMENT ON COLUMN DOCUMENT.PROCEDURE_TYPE IS '';
COMMENT ON COLUMN DOCUMENT.DOC_TEMPLATE IS '';
COMMENT ON COLUMN DOCUMENT.LANGUAGE IS '';
COMMENT ON COLUMN DOCUMENT.DOC_STAGE IS '';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.CATEGORY_CODE IS 'ID of category';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.CATEGORY_DESC IS 'Description of the category';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.ID IS '';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.CATEGORY_CODE IS '';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.CATEGORY_DESC IS '';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_CATEGORIES_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_CONTENT.ID IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.VERSION_ID IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.CATEGORY_CODE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.CONTENT IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.ACT_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.DOC_PURPOSE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.DOC_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.EEA_RELEVANCE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.TEMPLATE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.TITLE IS '';
COMMENT ON COLUMN DOCUMENT_CONTENT.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_CONTENT.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_CONTENT.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_CONTENT.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE.EXPORT_STATUS IS '';
COMMENT ON COLUMN DOCUMENT_MILESTONE.EXPORT_DATE IS '';
COMMENT ON COLUMN DOCUMENT_MILESTONE.JOB_ID IS '';
COMMENT ON COLUMN DOCUMENT_MILESTONE.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_MILESTONE.DOCUMENT_ID IS 'Document ID for which milestone is created';
COMMENT ON COLUMN DOCUMENT_MILESTONE.JOB_DATE IS 'Job id that creates this milestone';
COMMENT ON COLUMN DOCUMENT_MILESTONE.CLONED_MILESTONE_ID IS 'Milestone is cloned from another ID';
COMMENT ON COLUMN DOCUMENT_MILESTONE.MILESTONE_COMMENTS IS 'Overall comments for milestone';
COMMENT ON COLUMN DOCUMENT_MILESTONE.CONTENT IS 'The content of the milestone zip file in BLOB';
COMMENT ON COLUMN DOCUMENT_MILESTONE.STATUS IS 'Status for milestone creation';
COMMENT ON COLUMN DOCUMENT_MILESTONE.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_MILESTONE.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.MILESTONE_ID IS 'Milestone ID for which we list the documents contained';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.CONTAINED_DOCUMENTS IS 'List of documents contained in this milestone';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_MILESTONE_LIST.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.PROPERTY_NAME IS 'Name of the property that a document can have';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.DOC_CATEGORY_ID IS 'Category name for which this property is applied';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.OBJECT_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.PACKAGE_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.CATEGORY_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.CATEGORY_CODE IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.CATEGORY_DESC IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.NAME IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.VERSION_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.VERSION_LABEL IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.VERSION_SERIES_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.VERSION_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.PROP_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.PROPERTY_NAME IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.PROP_VALUE_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.PROPERTY_VALUE IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_PROPERTIES_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.VERSION_ID IS '';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.DOCUMENT_ID IS 'The document id for which we have values for property';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.PROPERTY_ID IS 'This is the property id for which we will store values';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.PROPERTY_VALUE IS 'The value of a property in character format';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_PROPERTY_VALUES.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_V.DOCUMENT_ID IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_OBJECT_ID IS '';
COMMENT ON COLUMN DOCUMENT_V.CATEGORY_ID IS '';
COMMENT ON COLUMN DOCUMENT_V.CATEGORY_CODE IS '';
COMMENT ON COLUMN DOCUMENT_V.CATEGORY_DESC IS '';
COMMENT ON COLUMN DOCUMENT_V.NAME IS '';
COMMENT ON COLUMN DOCUMENT_V.CLONED_FROM IS '';
COMMENT ON COLUMN DOCUMENT_V.REVISION_STATUS IS '';
COMMENT ON COLUMN DOCUMENT_V.CONTRIBUTION_STATUS IS '';
COMMENT ON COLUMN DOCUMENT_V.ORIGIN_REF IS '';
COMMENT ON COLUMN DOCUMENT_V.BASE_REVISION_ID IS '';
COMMENT ON COLUMN DOCUMENT_V.LIVE_DIFFING_REQUIRED IS '';
COMMENT ON COLUMN DOCUMENT_V.REF IS '';
COMMENT ON COLUMN DOCUMENT_V.PROCEDURE_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_TEMPLATE IS '';
COMMENT ON COLUMN DOCUMENT_V.LANGUAGE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_STAGE IS '';
COMMENT ON COLUMN DOCUMENT_V.IS_PRIVATE_WORKING_COPY IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_AUDIT_C_BY IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_AUDIT_C_DATE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_AUDIT_LAST_M_DATE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_AUDIT_LAST_M_BY IS '';
COMMENT ON COLUMN DOCUMENT_V.VERSION_LABEL IS '';
COMMENT ON COLUMN DOCUMENT_V.VERSION_SERIES_ID IS '';
COMMENT ON COLUMN DOCUMENT_V.VERSION_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_V.IS_LATEST_MAJOR_VERSION IS '';
COMMENT ON COLUMN DOCUMENT_V.IS_LATEST_VERSION IS '';
COMMENT ON COLUMN DOCUMENT_V.IS_MAJOR_VERSION IS '';
COMMENT ON COLUMN DOCUMENT_V.IS_VERSION_SERIES_CHECKED_OUT IS '';
COMMENT ON COLUMN DOCUMENT_V.CONTENT IS '';
COMMENT ON COLUMN DOCUMENT_V.ACT_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_PURPOSE IS '';
COMMENT ON COLUMN DOCUMENT_V.DOC_TYPE IS '';
COMMENT ON COLUMN DOCUMENT_V.EEA_RELEVANCE IS '';
COMMENT ON COLUMN DOCUMENT_V.TEMPLATE IS '';
COMMENT ON COLUMN DOCUMENT_V.TITLE IS '';
COMMENT ON COLUMN DOCUMENT_VERSION.IS_VERSION_SERIES_CHECKED_OUT IS 'Flag showing if version series is checked out or not 1/0';
COMMENT ON COLUMN DOCUMENT_VERSION.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN DOCUMENT_VERSION.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN DOCUMENT_VERSION.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN DOCUMENT_VERSION.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN DOCUMENT_VERSION.IS_IMMUTABLE IS '';
COMMENT ON COLUMN DOCUMENT_VERSION.DOCUMENT_ID IS '';
COMMENT ON COLUMN DOCUMENT_VERSION.ID IS 'Technical ID';
COMMENT ON COLUMN DOCUMENT_VERSION.VERSION_LABEL IS 'Version label';
COMMENT ON COLUMN DOCUMENT_VERSION.VERSION_SERIES_ID IS 'Version series ID';
COMMENT ON COLUMN DOCUMENT_VERSION.VERSION_TYPE IS 'Version type';
COMMENT ON COLUMN DOCUMENT_VERSION.IS_LATEST_MAJOR_VERSION IS 'Flag showing if is latest major version or not 1/0';
COMMENT ON COLUMN DOCUMENT_VERSION.IS_LATEST_VERSION IS 'Flag showing if is latest version or not 1/0';
COMMENT ON COLUMN DOCUMENT_VERSION.IS_MAJOR_VERSION IS 'Flag showing if is major version or not 1/0';
COMMENT ON COLUMN MILESTONE_LIST_V.PACKAGE_ID IS '';
COMMENT ON COLUMN MILESTONE_LIST_V.DOCUMENT_ID IS '';
COMMENT ON COLUMN MILESTONE_LIST_V.MILESTONE_ID IS '';
COMMENT ON COLUMN MILESTONE_LIST_V.CONTAINED_DOCUMENTS IS '';
COMMENT ON COLUMN MILESTONE_LIST_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN MILESTONE_LIST_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN MILESTONE_LIST_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN MILESTONE_LIST_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN MILESTONE_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN MILESTONE_V.DOCUMENT_ID IS '';
COMMENT ON COLUMN MILESTONE_V.PACKAGE_ID IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_OBJECT_ID IS '';
COMMENT ON COLUMN MILESTONE_V.CATEGORY_ID IS '';
COMMENT ON COLUMN MILESTONE_V.NAME IS '';
COMMENT ON COLUMN MILESTONE_V.CLONED_FROM IS '';
COMMENT ON COLUMN MILESTONE_V.REVISION_STATUS IS '';
COMMENT ON COLUMN MILESTONE_V.CONTRIBUTION_STATUS IS '';
COMMENT ON COLUMN MILESTONE_V.ORIGIN_REF IS '';
COMMENT ON COLUMN MILESTONE_V.BASE_REVISION_ID IS '';
COMMENT ON COLUMN MILESTONE_V.LIVE_DIFFING_REQUIRED IS '';
COMMENT ON COLUMN MILESTONE_V.REF IS '';
COMMENT ON COLUMN MILESTONE_V.PROCEDURE_TYPE IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_TEMPLATE IS '';
COMMENT ON COLUMN MILESTONE_V.LANGUAGE IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_STAGE IS '';
COMMENT ON COLUMN MILESTONE_V.IS_PRIVATE_WORKING_COPY IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_AUDIT_C_BY IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_AUDIT_C_DATE IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_AUDIT_LAST_M_DATE IS '';
COMMENT ON COLUMN MILESTONE_V.DOC_AUDIT_LAST_M_BY IS '';
COMMENT ON COLUMN MILESTONE_V.MILESTONE_ID IS '';
COMMENT ON COLUMN MILESTONE_V.JOB_DATE IS '';
COMMENT ON COLUMN MILESTONE_V.CLONED_MILESTONE_ID IS '';
COMMENT ON COLUMN MILESTONE_V.MILESTONE_COMMENTS IS '';
COMMENT ON COLUMN MILESTONE_V.CONTENT IS '';
COMMENT ON COLUMN MILESTONE_V.STATUS IS '';
COMMENT ON COLUMN MILESTONE_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN MILESTONE_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN MILESTONE_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN "PACKAGE".ORIGINAL_ID IS '';
COMMENT ON COLUMN "PACKAGE".IS_CLONED IS '';
COMMENT ON COLUMN "PACKAGE".CLONED_PACKAGE_NAME IS '';
COMMENT ON COLUMN "PACKAGE".CLONED_PACKAGE_ID IS '';
COMMENT ON COLUMN "PACKAGE".ID IS 'Technical ID';
COMMENT ON COLUMN "PACKAGE".OBJECT_ID IS 'Internal id for a proposal / PACKAGE';
COMMENT ON COLUMN "PACKAGE".NAME IS 'Name of the proposal';
COMMENT ON COLUMN "PACKAGE".REPOSITORY_ID IS 'Repository ID that this proposal belongs to';
COMMENT ON COLUMN "PACKAGE".AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN "PACKAGE".AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN "PACKAGE".AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN "PACKAGE".AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN PACKAGE_V.TEMPLATE IS '';
COMMENT ON COLUMN PACKAGE_V.TITLE IS '';
COMMENT ON COLUMN PACKAGE_V.PACKAGE_ID IS '';
COMMENT ON COLUMN PACKAGE_V.PKG_OBJECT_ID IS '';
COMMENT ON COLUMN PACKAGE_V.PACKAGE_NAME IS '';
COMMENT ON COLUMN PACKAGE_V.REPOSITORY_ID IS '';
COMMENT ON COLUMN PACKAGE_V.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN PACKAGE_V.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN PACKAGE_V.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN PACKAGE_V.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN PACKAGE_V.DOCUMENT_ID IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_OBJECT_ID IS '';
COMMENT ON COLUMN PACKAGE_V.CATEGORY_ID IS '';
COMMENT ON COLUMN PACKAGE_V.NAME IS '';
COMMENT ON COLUMN PACKAGE_V.CLONED_FROM IS '';
COMMENT ON COLUMN PACKAGE_V.REVISION_STATUS IS '';
COMMENT ON COLUMN PACKAGE_V.CONTRIBUTION_STATUS IS '';
COMMENT ON COLUMN PACKAGE_V.ORIGIN_REF IS '';
COMMENT ON COLUMN PACKAGE_V.BASE_REVISION_ID IS '';
COMMENT ON COLUMN PACKAGE_V.LIVE_DIFFING_REQUIRED IS '';
COMMENT ON COLUMN PACKAGE_V.REF IS '';
COMMENT ON COLUMN PACKAGE_V.PROCEDURE_TYPE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_TEMPLATE IS '';
COMMENT ON COLUMN PACKAGE_V.LANGUAGE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_STAGE IS '';
COMMENT ON COLUMN PACKAGE_V.IS_PRIVATE_WORKING_COPY IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_AUDIT_C_BY IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_AUDIT_C_DATE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_AUDIT_LAST_M_DATE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_AUDIT_LAST_M_BY IS '';
COMMENT ON COLUMN PACKAGE_V.VERSION_LABEL IS '';
COMMENT ON COLUMN PACKAGE_V.VERSION_SERIES_ID IS '';
COMMENT ON COLUMN PACKAGE_V.VERSION_TYPE IS '';
COMMENT ON COLUMN PACKAGE_V.IS_LATEST_MAJOR_VERSION IS '';
COMMENT ON COLUMN PACKAGE_V.IS_LATEST_VERSION IS '';
COMMENT ON COLUMN PACKAGE_V.IS_MAJOR_VERSION IS '';
COMMENT ON COLUMN PACKAGE_V.IS_VERSION_SERIES_CHECKED_OUT IS '';
COMMENT ON COLUMN PACKAGE_V.CONTENT IS '';
COMMENT ON COLUMN PACKAGE_V.ACT_TYPE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_PURPOSE IS '';
COMMENT ON COLUMN PACKAGE_V.DOC_TYPE IS '';
COMMENT ON COLUMN PACKAGE_V.EEA_RELEVANCE IS '';
COMMENT ON COLUMN PERMISSION.ID IS 'Technical ID';
COMMENT ON COLUMN PERMISSION.REPOSITORY_ID IS 'Repository ID for which this permission applies';
COMMENT ON COLUMN PERMISSION.NAME IS 'Name of the permission';
COMMENT ON COLUMN PERMISSION.DESCRIPTION IS 'Description of permission';
COMMENT ON COLUMN PERMISSION.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN PERMISSION.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN PERMISSION.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN PERMISSION.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
COMMENT ON COLUMN REPOSITORY.ID IS 'Technical ID';
COMMENT ON COLUMN REPOSITORY.CMIS_ID IS 'Internal ID';
COMMENT ON COLUMN REPOSITORY.NAME IS 'Name of the repository';
COMMENT ON COLUMN REPOSITORY.DESCRIPTION IS 'Description of the repository';
COMMENT ON COLUMN REPOSITORY.ALL_VERSIONS_SEARCHABLE IS 'Is repository searchable';
COMMENT ON COLUMN REPOSITORY.AUDIT_C_BY IS 'Audit column showing the user that created this record';
COMMENT ON COLUMN REPOSITORY.AUDIT_C_DATE IS 'Audit column showing creation timestamp for this record';
COMMENT ON COLUMN REPOSITORY.AUDIT_LAST_M_DATE IS 'Audit column showing the last modification timestamp for this record';
COMMENT ON COLUMN REPOSITORY.AUDIT_LAST_M_BY IS 'Audit column showing user who last modified record';
quit;