#
POST https://api.clearlydefined.io/notices
Content-Type: application/json

{
  "coordinates": [
    "npm/npmjs/@socket.io/component-emitter/3.1.0",
    "npm/npmjs/@types/cookie/0.4.1",
    "npm/npmjs/@types/cors/2.8.13",
    "npm/npmjs/@types/node/18.14.2",
    "npm/npmjs/-/abbrev/1.1.1",
    "npm/npmjs/-/accepts/1.3.8",
    "npm/npmjs/-/accord/0.26.4",
    "npm/npmjs/-/align-text/0.1.4",
    "npm/npmjs/-/amdefine/1.0.1",
    "npm/npmjs/-/angular-multiple-select/1.1.3",
    "npm/npmjs/-/annotate-client/1.84.0",
    "npm/npmjs/-/ansi-cyan/0.1.1",
    "npm/npmjs/-/ansi-gray/0.1.1",
    "npm/npmjs/-/ansi-red/0.1.1",
    "npm/npmjs/-/ansi-regex/5.0.1",
    "npm/npmjs/-/ansi-styles/4.3.0",
    "npm/npmjs/-/ansi-wrap/0.1.0",
    "npm/npmjs/-/anymatch/3.1.3",
    "npm/npmjs/-/append-buffer/1.0.2",
    "npm/npmjs/-/archy/1.0.0",
    "npm/npmjs/-/arr-diff/4.0.0",
    "npm/npmjs/-/arr-flatten/1.1.0",
    "npm/npmjs/-/arr-union/3.1.0",
    "npm/npmjs/-/array-differ/1.0.0",
    "npm/npmjs/-/array-each/1.0.1",
    "npm/npmjs/-/array-find-index/1.0.2",
    "npm/npmjs/-/array-slice/1.1.0",
    "npm/npmjs/-/array-union/1.0.2",
    "npm/npmjs/-/array-uniq/1.0.3",
    "npm/npmjs/-/array-unique/0.3.2",
    "npm/npmjs/-/arrify/1.0.1",
    "npm/npmjs/-/asap/2.0.6",
    "npm/npmjs/-/assign-symbols/1.0.0",
    "npm/npmjs/-/async-each-series/0.1.1",
    "npm/npmjs/-/async/2.6.4",
    "npm/npmjs/-/atob/2.1.2",
    "npm/npmjs/-/axios/0.21.4",
    "npm/npmjs/-/balanced-match/1.0.2",
    "npm/npmjs/-/base64id/2.0.0",
    "npm/npmjs/-/base/0.11.2",
    "npm/npmjs/-/batch/0.6.1",
    "npm/npmjs/-/beeper/1.1.1",
    "npm/npmjs/-/binary-extensions/2.2.0",
    "npm/npmjs/-/body-parser/1.14.2",
    "npm/npmjs/-/bower/1.8.14",
    "npm/npmjs/-/brace-expansion/1.1.11",
    "npm/npmjs/-/braces/3.0.2",
    "npm/npmjs/-/browser-sync-client/2.28.1",
    "npm/npmjs/-/browser-sync-ui/2.28.1",
    "npm/npmjs/-/browser-sync/2.28.1",
    "npm/npmjs/-/bs-recipes/1.3.4",
    "npm/npmjs/-/bs-snippet-injector/2.0.1",
    "npm/npmjs/-/buffer-equal/1.0.1",
    "npm/npmjs/-/bufferutil/4.0.7",
    "npm/npmjs/-/bytes/3.1.2",
    "npm/npmjs/-/cache-base/1.0.1",
    "npm/npmjs/-/call-bind/1.0.2",
    "npm/npmjs/-/camelcase-keys/2.1.0",
    "npm/npmjs/-/camelcase/2.1.1",
    "npm/npmjs/-/center-align/0.1.3",
    "npm/npmjs/-/chalk/4.1.2",
    "npm/npmjs/-/char-props/0.1.5",
    "npm/npmjs/-/chokidar/3.5.3",
    "npm/npmjs/-/ckeditor4/4.21.0",
    "npm/npmjs/-/class-utils/0.3.6",
    "npm/npmjs/-/clean-css/3.4.28",
    "npm/npmjs/-/cliui/8.0.1",
    "npm/npmjs/-/clone-buffer/1.0.0",
    "npm/npmjs/-/clone-stats/1.0.0",
    "npm/npmjs/-/clone/2.1.2",
    "npm/npmjs/-/cloneable-readable/1.1.3",
    "npm/npmjs/-/collection-visit/1.0.0",
    "npm/npmjs/-/color-convert/2.0.1",
    "npm/npmjs/-/color-name/1.1.4",
    "npm/npmjs/-/color-support/1.1.3",
    "npm/npmjs/-/commander/2.8.1",
    "npm/npmjs/-/component-emitter/1.3.0",
    "npm/npmjs/-/concat-map/0.0.1",
    "npm/npmjs/-/concat-with-sourcemaps/1.1.0",
    "npm/npmjs/-/connect-history-api-fallback/1.6.0",
    "npm/npmjs/-/connect/3.6.6",
    "npm/npmjs/-/content-type/1.0.5",
    "npm/npmjs/-/convert-source-map/1.9.0",
    "npm/npmjs/-/cookie/0.4.2",
    "npm/npmjs/-/copy-descriptor/0.1.1",
    "npm/npmjs/-/core-util-is/1.0.3",
    "npm/npmjs/-/cors/2.8.5",
    "npm/npmjs/-/css-parse/2.0.0",
    "npm/npmjs/-/css/2.2.4",
    "npm/npmjs/-/csv-parser/3.0.0",
    "npm/npmjs/-/currently-unhandled/0.4.1",
    "npm/npmjs/-/dateformat/2.2.0",
    "npm/npmjs/-/debug/4.3.4",
    "npm/npmjs/-/debuglog/1.0.1",
    "npm/npmjs/-/decamelize/1.2.0",
    "npm/npmjs/-/decode-uri-component/0.2.2",
    "npm/npmjs/-/defaults/1.0.4",
    "npm/npmjs/-/define-properties/1.2.0",
    "npm/npmjs/-/define-property/2.0.2",
    "npm/npmjs/-/depd/2.0.0",
    "npm/npmjs/-/deprecated/0.0.1",
    "npm/npmjs/-/destroy/1.0.4",
    "npm/npmjs/-/detect-file/1.0.0",
    "npm/npmjs/-/dev-ip/1.0.1",
    "npm/npmjs/-/dezalgo/1.0.4",
    "npm/npmjs/-/duplexer2/0.0.2",
    "npm/npmjs/-/duplexer/0.1.2",
    "npm/npmjs/-/duplexify/3.7.1",
    "npm/npmjs/-/easy-extender/2.3.4",
    "npm/npmjs/-/eazy-logger/4.0.0",
    "npm/npmjs/-/ee-first/1.1.1",
    "npm/npmjs/-/emoji-regex/8.0.0",
    "npm/npmjs/-/encodeurl/1.0.2",
    "npm/npmjs/-/end-of-stream/1.4.4",
    "npm/npmjs/-/engine.io-client/6.4.0",
    "npm/npmjs/-/engine.io-parser/5.0.6",
    "npm/npmjs/-/engine.io/6.4.1",
    "npm/npmjs/-/error-ex/1.3.2",
    "npm/npmjs/-/escalade/3.1.1",
    "npm/npmjs/-/escape-html/1.0.3",
    "npm/npmjs/-/escape-string-regexp/1.0.5",
    "npm/npmjs/-/etag/1.8.1",
    "npm/npmjs/-/event-stream/4.0.1",
    "npm/npmjs/-/eventemitter3/4.0.7",
    "npm/npmjs/-/expand-brackets/2.1.4",
    "npm/npmjs/-/expand-tilde/2.0.2",
    "npm/npmjs/-/extend-shallow/3.0.2",
    "npm/npmjs/-/extend/3.0.2",
    "npm/npmjs/-/extglob/2.0.4",
    "npm/npmjs/-/fancy-log/1.3.3",
    "npm/npmjs/-/faye-websocket/0.7.3",
    "npm/npmjs/-/filesize/2.0.4",
    "npm/npmjs/-/fill-range/7.0.1",
    "npm/npmjs/-/finalhandler/1.1.0",
    "npm/npmjs/-/find-index/0.1.1",
    "npm/npmjs/-/find-up/1.1.2",
    "npm/npmjs/-/findup-sync/2.0.0",
    "npm/npmjs/-/fined/1.2.0",
    "npm/npmjs/-/first-chunk-stream/1.0.0",
    "npm/npmjs/-/flagged-respawn/1.0.1",
    "npm/npmjs/-/flush-write-stream/1.1.1",
    "npm/npmjs/-/follow-redirects/1.15.2",
    "npm/npmjs/-/for-in/1.0.2",
    "npm/npmjs/-/for-own/1.0.0",
    "npm/npmjs/-/fragment-cache/0.2.1",
    "npm/npmjs/-/fresh/0.5.2",
    "npm/npmjs/-/from/0.1.7",
    "npm/npmjs/-/fs-extra/3.0.1",
    "npm/npmjs/-/fs-mkdirp-stream/1.0.0",
    "npm/npmjs/-/fs.realpath/1.0.0",
    "npm/npmjs/-/function-bind/1.1.1",
    "npm/npmjs/-/gaze/0.5.2",
    "npm/npmjs/-/get-caller-file/2.0.5",
    "npm/npmjs/-/get-intrinsic/1.2.0",
    "npm/npmjs/-/get-stdin/4.0.1",
    "npm/npmjs/-/get-value/2.0.6",
    "npm/npmjs/-/glob-parent/5.1.2",
    "npm/npmjs/-/glob-stream/6.1.0",
    "npm/npmjs/-/glob-watcher/0.0.6",
    "npm/npmjs/-/glob2base/0.0.12",
    "npm/npmjs/-/glob/7.2.3",
    "npm/npmjs/-/global-modules/1.0.0",
    "npm/npmjs/-/global-prefix/1.0.2",
    "npm/npmjs/-/globby/2.1.0",
    "npm/npmjs/-/globule/0.1.0",
    "npm/npmjs/-/glogg/1.0.2",
    "npm/npmjs/-/glyphicons-only-bootstrap/1.0.1",
    "npm/npmjs/-/graceful-fs/4.2.10",
    "npm/npmjs/-/graceful-readlink/1.0.1",
    "npm/npmjs/-/gulp-angular-templatecache/1.9.1",
    "npm/npmjs/-/gulp-concat/2.6.1",
    "npm/npmjs/-/gulp-cssmin/0.1.7",
    "npm/npmjs/-/gulp-footer/1.0.5",
    "npm/npmjs/-/gulp-header/1.8.2",
    "npm/npmjs/-/gulp-inject/3.0.0",
    "npm/npmjs/-/gulp-jsmin/0.1.5",
    "npm/npmjs/-/gulp-livereload/3.8.1",
    "npm/npmjs/-/gulp-rename/1.4.0",
    "npm/npmjs/-/gulp-stylus/2.7.1",
    "npm/npmjs/-/gulp-util/3.0.8",
    "npm/npmjs/-/gulp/3.9.1",
    "npm/npmjs/-/gulplog/1.0.0",
    "npm/npmjs/-/has-ansi/2.0.0",
    "npm/npmjs/-/has-flag/4.0.0",
    "npm/npmjs/-/has-gulplog/0.1.0",
    "npm/npmjs/-/has-property-descriptors/1.0.0",
    "npm/npmjs/-/has-symbols/1.0.3",
    "npm/npmjs/-/has-value/1.0.0",
    "npm/npmjs/-/has-values/1.0.0",
    "npm/npmjs/-/has/1.0.3",
    "npm/npmjs/-/homedir-polyfill/1.0.3",
    "npm/npmjs/-/hosted-git-info/2.8.9",
    "npm/npmjs/-/http-errors/2.0.0",
    "npm/npmjs/-/http-parser-js/0.5.8",
    "npm/npmjs/-/http-proxy/1.18.1",
    "npm/npmjs/-/iconv-lite/0.4.24",
    "npm/npmjs/-/immutable/3.8.2",
    "npm/npmjs/-/indent-string/2.1.0",
    "npm/npmjs/-/indx/0.2.3",
    "npm/npmjs/-/inflight/1.0.6",
    "npm/npmjs/-/inherits/2.0.4",
    "npm/npmjs/-/ini/1.3.8",
    "npm/npmjs/-/interpret/1.4.0",
    "npm/npmjs/-/is-absolute/1.0.0",
    "npm/npmjs/-/is-accessor-descriptor/1.0.0",
    "npm/npmjs/-/is-arrayish/0.2.1",
    "npm/npmjs/-/is-binary-path/2.1.0",
    "npm/npmjs/-/is-buffer/1.1.6",
    "npm/npmjs/-/is-core-module/2.11.0",
    "npm/npmjs/-/is-data-descriptor/1.0.0",
    "npm/npmjs/-/is-descriptor/1.0.2",
    "npm/npmjs/-/is-extendable/1.0.1",
    "npm/npmjs/-/is-extglob/2.1.1",
    "npm/npmjs/-/is-finite/1.1.0",
    "npm/npmjs/-/is-fullwidth-code-point/3.0.0",
    "npm/npmjs/-/is-glob/4.0.3",
    "npm/npmjs/-/is-negated-glob/1.0.0",
    "npm/npmjs/-/is-number-like/1.0.8",
    "npm/npmjs/-/is-number/7.0.0",
    "npm/npmjs/-/is-plain-object/2.0.4",
    "npm/npmjs/-/is-relative/1.0.0",
    "npm/npmjs/-/is-unc-path/1.0.0",
    "npm/npmjs/-/is-utf8/0.2.1",
    "npm/npmjs/-/is-valid-glob/1.0.0",
    "npm/npmjs/-/is-windows/1.0.2",
    "npm/npmjs/-/is-wsl/1.1.0",
    "npm/npmjs/-/isarray/1.0.0",
    "npm/npmjs/-/isexe/2.0.0",
    "npm/npmjs/-/isobject/3.0.1",
    "npm/npmjs/-/js-string-escape/1.0.1",
    "npm/npmjs/-/jsmin-sourcemap/0.16.0",
    "npm/npmjs/-/jsmin2/1.1.9",
    "npm/npmjs/-/json-parse-even-better-errors/2.3.1",
    "npm/npmjs/-/json-stable-stringify-without-jsonify/1.0.1",
    "npm/npmjs/-/jsonfile/3.0.1",
    "npm/npmjs/-/kind-of/6.0.3",
    "npm/npmjs/-/lazy-cache/1.0.4",
    "npm/npmjs/-/lazystream/1.0.1",
    "npm/npmjs/-/lead/1.0.0",
    "npm/npmjs/-/license-checker/25.0.1",
    "npm/npmjs/-/liftoff/2.5.0",
    "npm/npmjs/-/limiter/1.1.5",
    "npm/npmjs/-/livereload-js/2.4.0",
    "npm/npmjs/-/load-json-file/1.1.0",
    "npm/npmjs/-/localtunnel/2.0.2",
    "npm/npmjs/-/lodash._baseassign/3.2.0",
    "npm/npmjs/-/lodash._basecopy/3.0.1",
    "npm/npmjs/-/lodash._basetostring/3.0.1",
    "npm/npmjs/-/lodash._basevalues/3.0.0",
    "npm/npmjs/-/lodash._bindcallback/3.0.1",
    "npm/npmjs/-/lodash._createassigner/3.1.1",
    "npm/npmjs/-/lodash._escapehtmlchar/2.4.1",
    "npm/npmjs/-/lodash._escapestringchar/2.4.1",
    "npm/npmjs/-/lodash._getnative/3.9.1",
    "npm/npmjs/-/lodash._htmlescapes/2.4.1",
    "npm/npmjs/-/lodash._isiterateecall/3.0.9",
    "npm/npmjs/-/lodash._isnative/2.4.1",
    "npm/npmjs/-/lodash._objecttypes/2.4.1",
    "npm/npmjs/-/lodash._reescape/3.0.0",
    "npm/npmjs/-/lodash._reevaluate/3.0.0",
    "npm/npmjs/-/lodash._reinterpolate/3.0.0",
    "npm/npmjs/-/lodash._reunescapedhtml/2.4.1",
    "npm/npmjs/-/lodash._root/3.0.1",
    "npm/npmjs/-/lodash._shimkeys/2.4.1",
    "npm/npmjs/-/lodash.assign/4.2.0",
    "npm/npmjs/-/lodash.clone/4.5.0",
    "npm/npmjs/-/lodash.defaults/4.2.0",
    "npm/npmjs/-/lodash.escape/3.2.0",
    "npm/npmjs/-/lodash.flatten/4.4.0",
    "npm/npmjs/-/lodash.isarguments/3.1.0",
    "npm/npmjs/-/lodash.isarray/3.0.4",
    "npm/npmjs/-/lodash.isfinite/3.3.2",
    "npm/npmjs/-/lodash.isobject/2.4.1",
    "npm/npmjs/-/lodash.keys/3.1.2",
    "npm/npmjs/-/lodash.merge/4.6.2",
    "npm/npmjs/-/lodash.partialright/4.2.1",
    "npm/npmjs/-/lodash.pick/4.4.0",
    "npm/npmjs/-/lodash.restparam/3.6.1",
    "npm/npmjs/-/lodash.template/3.6.2",
    "npm/npmjs/-/lodash.templatesettings/3.1.1",
    "npm/npmjs/-/lodash.uniq/4.5.0",
    "npm/npmjs/-/lodash.values/2.4.1",
    "npm/npmjs/-/lodash/4.17.21",
    "npm/npmjs/-/longest/1.0.1",
    "npm/npmjs/-/loud-rejection/1.6.0",
    "npm/npmjs/-/lru-cache/2.7.3",
    "npm/npmjs/-/main-bower-files/2.13.3",
    "npm/npmjs/-/make-iterator/1.0.1",
    "npm/npmjs/-/map-cache/0.2.2",
    "npm/npmjs/-/map-obj/1.0.1",
    "npm/npmjs/-/map-stream/0.1.0",
    "npm/npmjs/-/map-visit/1.0.0",
    "npm/npmjs/-/media-typer/0.3.0",
    "npm/npmjs/-/meow/3.7.0",
    "npm/npmjs/-/micromatch/4.0.5",
    "npm/npmjs/-/mime-db/1.52.0",
    "npm/npmjs/-/mime-types/2.1.35",
    "npm/npmjs/-/mime/1.4.1",
    "npm/npmjs/-/mini-lr/0.1.9",
    "npm/npmjs/-/minimatch/3.1.2",
    "npm/npmjs/-/minimist/1.2.8",
    "npm/npmjs/-/mitt/1.2.0",
    "npm/npmjs/-/mixin-deep/1.3.2",
    "npm/npmjs/-/mkdirp/1.0.4",
    "npm/npmjs/-/ms/2.1.3",
    "npm/npmjs/-/multimatch/2.1.0",
    "npm/npmjs/-/multipipe/0.1.2",
    "npm/npmjs/-/nanomatch/1.2.13",
    "npm/npmjs/-/natives/1.1.6",
    "npm/npmjs/-/negotiator/0.6.3",
    "npm/npmjs/-/node-gyp-build/4.6.0",
    "npm/npmjs/-/nopt/4.0.3",
    "npm/npmjs/-/normalize-package-data/2.5.0",
    "npm/npmjs/-/normalize-path/3.0.0",
    "npm/npmjs/-/now-and-later/2.0.1",
    "npm/npmjs/-/npm-normalize-package-bin/1.0.1",
    "npm/npmjs/-/object-assign/4.1.1",
    "npm/npmjs/-/object-copy/0.1.0",
    "npm/npmjs/-/object-inspect/1.12.3",
    "npm/npmjs/-/object-keys/1.1.1",
    "npm/npmjs/-/object-visit/1.0.1",
    "npm/npmjs/-/object.assign/4.1.4",
    "npm/npmjs/-/object.defaults/1.1.0",
    "npm/npmjs/-/object.map/1.0.1",
    "npm/npmjs/-/object.pick/1.3.0",
    "npm/npmjs/-/on-finished/2.3.0",
    "npm/npmjs/-/once/1.4.0",
    "npm/npmjs/-/openurl/1.1.1",
    "npm/npmjs/-/opn/5.3.0",
    "npm/npmjs/-/orchestrator/0.3.8",
    "npm/npmjs/-/ordered-read-streams/1.0.1",
    "npm/npmjs/-/os-homedir/1.0.2",
    "npm/npmjs/-/os-tmpdir/1.0.2",
    "npm/npmjs/-/osenv/0.1.5",
    "npm/npmjs/-/parse-filepath/1.0.2",
    "npm/npmjs/-/parse-json/2.2.0",
    "npm/npmjs/-/parse-node-version/1.0.1",
    "npm/npmjs/-/parse-passwd/1.0.0",
    "npm/npmjs/-/parseurl/1.3.3",
    "npm/npmjs/-/pascalcase/0.1.1",
    "npm/npmjs/-/path-dirname/1.0.2",
    "npm/npmjs/-/path-exists/2.1.0",
    "npm/npmjs/-/path-is-absolute/1.0.1",
    "npm/npmjs/-/path-parse/1.0.7",
    "npm/npmjs/-/path-root-regex/0.1.2",
    "npm/npmjs/-/path-root/0.1.1",
    "npm/npmjs/-/path-type/1.1.0",
    "npm/npmjs/-/pause-stream/0.0.11",
    "npm/npmjs/-/picomatch/2.3.1",
    "npm/npmjs/-/pify/2.3.0",
    "npm/npmjs/-/pinkie-promise/2.0.1",
    "npm/npmjs/-/pinkie/2.0.4",
    "npm/npmjs/-/plugin-error/0.1.2",
    "npm/npmjs/-/portscanner/2.2.0",
    "npm/npmjs/-/posix-character-classes/0.1.1",
    "npm/npmjs/-/pretty-hrtime/1.0.3",
    "npm/npmjs/-/process-nextick-args/2.0.1",
    "npm/npmjs/-/pump/2.0.1",
    "npm/npmjs/-/pumpify/1.5.1",
    "npm/npmjs/-/qs/6.11.0",
    "npm/npmjs/-/range-parser/1.2.1",
    "npm/npmjs/-/raw-body/2.5.2",
    "npm/npmjs/-/read-installed/4.0.3",
    "npm/npmjs/-/read-package-json/2.1.2",
    "npm/npmjs/-/read-pkg-up/1.0.1",
    "npm/npmjs/-/read-pkg/1.1.0",
    "npm/npmjs/-/readable-stream/2.3.8",
    "npm/npmjs/-/readdir-scoped-modules/1.1.0",
    "npm/npmjs/-/readdirp/3.6.0",
    "npm/npmjs/-/rechoir/0.6.2",
    "npm/npmjs/-/redent/1.0.0",
    "npm/npmjs/-/regex-not/1.0.2",
    "npm/npmjs/-/remove-bom-buffer/3.0.0",
    "npm/npmjs/-/remove-bom-stream/1.2.0",
    "npm/npmjs/-/remove-trailing-separator/1.1.0",
    "npm/npmjs/-/repeat-element/1.1.4",
    "npm/npmjs/-/repeat-string/1.6.1",
    "npm/npmjs/-/repeating/2.0.1",
    "npm/npmjs/-/replace-ext/1.0.1",
    "npm/npmjs/-/require-directory/2.1.1",
    "npm/npmjs/-/requires-port/1.0.0",
    "npm/npmjs/-/resolve-dir/1.0.1",
    "npm/npmjs/-/resolve-options/1.1.0",
    "npm/npmjs/-/resolve-url/0.2.1",
    "npm/npmjs/-/resolve/1.22.1",
    "npm/npmjs/-/resp-modifier/6.0.2",
    "npm/npmjs/-/ret/0.1.15",
    "npm/npmjs/-/right-align/0.1.3",
    "npm/npmjs/-/rx/4.1.0",
    "npm/npmjs/-/rxjs/5.5.12",
    "npm/npmjs/-/safe-buffer/5.2.1",
    "npm/npmjs/-/safe-regex/1.1.0",
    "npm/npmjs/-/safer-buffer/2.1.2",
    "npm/npmjs/-/sax/1.2.4",
    "npm/npmjs/-/semver/6.3.0",
    "npm/npmjs/-/send/0.16.2",
    "npm/npmjs/-/sequencify/0.0.7",
    "npm/npmjs/-/serve-index/1.9.1",
    "npm/npmjs/-/serve-static/1.13.2",
    "npm/npmjs/-/server-destroy/1.0.1",
    "npm/npmjs/-/set-value/2.0.1",
    "npm/npmjs/-/setprototypeof/1.2.0",
    "npm/npmjs/-/side-channel/1.0.4",
    "npm/npmjs/-/sigmund/1.0.1",
    "npm/npmjs/-/signal-exit/3.0.7",
    "npm/npmjs/-/slide/1.1.6",
    "npm/npmjs/-/snapdragon-node/2.1.1",
    "npm/npmjs/-/snapdragon-util/3.0.1",
    "npm/npmjs/-/snapdragon/0.8.2",
    "npm/npmjs/-/socket.io-adapter/2.5.2",
    "npm/npmjs/-/socket.io-client/4.6.1",
    "npm/npmjs/-/socket.io-parser/4.2.2",
    "npm/npmjs/-/socket.io/4.6.1",
    "npm/npmjs/-/source-map-index-generator/0.1.2",
    "npm/npmjs/-/source-map-resolve/0.5.3",
    "npm/npmjs/-/source-map-url/0.4.1",
    "npm/npmjs/-/source-map/0.7.4",
    "npm/npmjs/-/sparkles/1.0.1",
    "npm/npmjs/-/spdx-compare/1.0.0",
    "npm/npmjs/-/spdx-correct/3.1.1",
    "npm/npmjs/-/spdx-exceptions/2.3.0",
    "npm/npmjs/-/spdx-expression-parse/3.0.1",
    "npm/npmjs/-/spdx-license-ids/3.0.12",
    "npm/npmjs/-/spdx-ranges/2.1.1",
    "npm/npmjs/-/spdx-satisfies/4.0.1",
    "npm/npmjs/-/split-string/3.1.0",
    "npm/npmjs/-/split/1.0.1",
    "npm/npmjs/-/static-extend/0.1.2",
    "npm/npmjs/-/statuses/2.0.1",
    "npm/npmjs/-/stream-combiner/0.2.2",
    "npm/npmjs/-/stream-consume/0.1.1",
    "npm/npmjs/-/stream-shift/1.0.1",
    "npm/npmjs/-/stream-throttle/0.1.3",
    "npm/npmjs/-/string-width/4.2.3",
    "npm/npmjs/-/string_decoder/1.1.1",
    "npm/npmjs/-/strip-ansi/6.0.1",
    "npm/npmjs/-/strip-bom/2.0.0",
    "npm/npmjs/-/strip-indent/1.0.1",
    "npm/npmjs/-/strip-json-comments/1.0.4",
    "npm/npmjs/-/stylus/0.54.8",
    "npm/npmjs/-/supports-color/7.2.0",
    "npm/npmjs/-/supports-preserve-symlinks-flag/1.0.0",
    "npm/npmjs/-/symbol-observable/1.0.1",
    "npm/npmjs/-/temp-write/0.1.1",
    "npm/npmjs/-/tempfile/0.1.3",
    "npm/npmjs/-/through2-filter/3.0.0",
    "npm/npmjs/-/through2/2.0.5",
    "npm/npmjs/-/through/2.3.8",
    "npm/npmjs/-/tildify/1.2.0",
    "npm/npmjs/-/time-stamp/1.1.0",
    "npm/npmjs/-/to-absolute-glob/2.0.2",
    "npm/npmjs/-/to-object-path/0.3.0",
    "npm/npmjs/-/to-regex-range/5.0.1",
    "npm/npmjs/-/to-regex/3.0.2",
    "npm/npmjs/-/to-through/2.0.0",
    "npm/npmjs/-/toidentifier/1.0.1",
    "npm/npmjs/-/treeify/1.1.0",
    "npm/npmjs/-/trim-newlines/1.0.0",
    "npm/npmjs/-/type-is/1.6.18",
    "npm/npmjs/-/typescript/4.9.5",
    "npm/npmjs/-/ua-parser-js/1.0.33",
    "npm/npmjs/-/uglify-js/2.8.29",
    "npm/npmjs/-/uglify-to-browserify/1.0.2",
    "npm/npmjs/-/unc-path-regex/0.1.2",
    "npm/npmjs/-/union-value/1.0.1",
    "npm/npmjs/-/unique-stream/2.3.1",
    "npm/npmjs/-/universalify/0.1.2",
    "npm/npmjs/-/unpipe/1.0.0",
    "npm/npmjs/-/unset-value/1.0.0",
    "npm/npmjs/-/urix/0.1.0",
    "npm/npmjs/-/use/3.1.1",
    "npm/npmjs/-/user-home/1.1.1",
    "npm/npmjs/-/utf-8-validate/5.0.10",
    "npm/npmjs/-/util-deprecate/1.0.2",
    "npm/npmjs/-/util-extend/1.0.3",
    "npm/npmjs/-/utils-merge/1.0.1",
    "npm/npmjs/-/uuid/1.4.2",
    "npm/npmjs/-/v8flags/2.1.1",
    "npm/npmjs/-/validate-npm-package-license/3.0.4",
    "npm/npmjs/-/value-or-function/3.0.0",
    "npm/npmjs/-/vary/1.1.2",
    "npm/npmjs/-/vinyl-fs/3.0.3",
    "npm/npmjs/-/vinyl-sourcemap/1.1.0",
    "npm/npmjs/-/vinyl-sourcemaps-apply/0.2.1",
    "npm/npmjs/-/vinyl/2.2.1",
    "npm/npmjs/-/websocket-driver/0.7.4",
    "npm/npmjs/-/websocket-extensions/0.1.4",
    "npm/npmjs/-/when/3.7.8",
    "npm/npmjs/-/which/1.3.1",
    "npm/npmjs/-/window-size/0.1.0",
    "npm/npmjs/-/wordwrap/0.0.2",
    "npm/npmjs/-/wrap-ansi/7.0.0",
    "npm/npmjs/-/wrappy/1.0.2",
    "npm/npmjs/-/ws/8.11.0",
    "npm/npmjs/-/xmlhttprequest-ssl/2.0.0",
    "npm/npmjs/-/xtend/4.0.2",
    "npm/npmjs/-/y18n/5.0.8",
    "npm/npmjs/-/yargs-parser/21.1.1",
    "npm/npmjs/-/yargs/3.10.0"
  ],
  "renderer": "json",
  "options": {}
}

###