CREATE USER LEOS_REPOSITORY IDENTIFIED BY LEOS_REPOSITORY;
GRANT CONNECT TO LEOS_REPOSITORY;
GRANT CREATE SESSION TO LEOS_REPOSITORY;
GRANT DBA TO LEOS_REPOSITORY;
CREATE TABLESPACE LEOS_REPOSITORY
    DATAFILE 'LEOS_REPOSITORY.DBF'
    size 1G autoextend on next 1G maxsize 33554416K;
ALTER USER LEOS_REPOSITORY DEFAULT TABLESPACE LEOS_REPOSITORY;