spring.profiles.active=@repository.db@
spring.main.banner-mode=off

server.servlet.context-path=/repository
# This port is used only when running as boot application
server.port=9097

logging.file=repository.log