

server.port=9096
server.servlet.context-path=/akn4euutil
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.codec.max-in-memory-size=50MB
spring.main.banner-mode=off
leos.freemarker.xml.to.html=xml_to_html.ftl
leos.freemarker.ftl.export.legiswrite.pdf=pdf.ftl
leos.freemarker.ftl.export.legiswrite.word=word.ftl
leos.freemarker.ftl.export.legiswrite.word.annex=annex.ftl

# LEOS core api urls
leos.rest.core.api.url=@leos.rest.core.api.url@
leos.rest.core.api.html.renditions.uri=/getHtmlRenditions

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.health.diskspace.enabled=false
management.health.ssl.enabled=false

leos.rest.core.api.con.validation.uri=/conValidation

notification.functional.mailbox=email@email.com