# akn4euutil logging
leos.log.level=INFO
leos.log.contextName=akn4euutils
leos.log.filePrefix=akn4euutils
leos.log.path=./logs

server.port=9096
server.servlet.context-path=/akn4euutil
server.cors.enabled=false
# Multiple origins are allowed. Separate by comma. Example: http://host1:8080/,http://host2:8080/,http://host3:8080/
# Set to "*" to allow all origins.
server.cors.allowedOrigins=*
server.cors.allowedHeaders=Origin,Content-Type,Authorization,Accept,Access-Control-Request-Header,Access-Control-Request-Method,Access-Control-Allow-Origin
server.cors.allowCredentials=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.codec.max-in-memory-size=50MB
spring.main.banner-mode=off
leos.freemarker.xml.to.html=xml_to_html.ftl

# LEOS core api urls
leos.rest.core.api.url=@leos.rest.core.api.url@
leos.rest.core.api.html.renditions.uri=/getHtmlRenditions