spring.profiles.active=@repository.db@
spring.main.banner-mode=off

server.servlet.context-path=/repository
# This port is used only when running as boot application
server.port=9097

repository.template.path=@repository.template.path@
repository.workspace.path=@repository.workspace.path@
repository.data.script.path=@repository.data.script.path@

logging.file=repository.log

repository.jwt.auth.enabled=@repository.jwt.auth.enabled@
repository.jwt.auth.issuer.id=@repository.jwt.auth.issuer.id@
repository.jwt.auth.access.token.expiration.min=@repository.jwt.auth.access.token.expiration.min@

repository.jwt.auth.user.details.cache.expiration.min=@repository.jwt.auth.user.details.cache.expiration.min@
repository.jwt.auth.user.details.url=@repository.jwt.auth.user.details.url@

repository.jwt.auth.clients=@repository.jwt.auth.clients@
repository.jwt.auth.client.leos.id=@repository.jwt.auth.client.leos.id@