spring.profiles.active=h2
server.servlet.context-path=/repository
spring.main.banner-mode=off
logging.file=repository.log

# DDL generation
spring.jpa.hibernate.ddl-auto=update
trab.test=test
server.port=9097
debug=true
spring.devtools.restart.enabled=true

#logging.level.org.hibernate=trace
spring.h2.console.enabled=true
spring.jpa.open-in-view=false
