app.name=Repositpry App

app.controllers.package=eu.europa.ec.leos.repository.controllers
## Maven info
app.build.timestamp=@maven.build.timestamp@

## GIT plugin info
app.version=@project.version@
app.build.plan.revision=@git.commit.id@
app.build.repo.url=@git.remote.origin.url@
app.build.repo.branchName=@git.branch@

## Bamboo info
## Inject the ci.x properties from you CI build pipeline
app.build.planName=@ci.shortPlanName@
app.build.number=@ci.buildNumber@
app.build.repo.name=@ci.repo.name@

## OTHERS
git.branch=@git.branch@
git.commit.id=@git.commit.id@
