export const SAVE_DOCUMENT_SECTION_ID = 'SAVE_DOCUMENT_VERSION_SECTION_ID';
export const SAVE_DOCUMENT_ACTION_ID = 'SAVE_DOCUMENT_VERSION_ACTION_ID';
export const IMPORT_OJ_SECTION_ID = 'IMPORT_OJ_SECTION_ID';
export const IMPORT_OJ_ACTION_ID = 'IMPORT_OJ_ACTION_ID';
export const EXPORT_SECTION_ID = 'EXPORT_SECTION_ID';
export const EXPORT_SECTION_DROPDOWN_ID = 'EXPORT_SECTION_DROPDOWN';
export const EXPORT_DOCUMENT_ACTION_ID = 'EXPORT_VERSION_ACTION_ID';
export const EXPORT_DROPDOWN_EXPORT_VERSION_ID =
  'EXPORT_DROPDOWN_EXPORT_VERSION_ID';
export const EXPORT_DROPDOWN_EXPORT_VERSION_WITH_ANNOTATIONS_ID =
  'EXPORT_DROPDOWN_EXPORT_VERSION_WITH_ANNOTATIONS_ID';
export const EXPORT_DROPDOWN_EXPORT_CLEAN_VERSION_ID =
  'EXPORT_DROPDOWN_EXPORT_CLEAN_VERSION_ID';
export const EXPORT_DROPDOWN_EXPORT_TO_ECONSILIUM =
  'EXPORT_DROPDOWN_EXPORT_TO_ECONSILIUM';
export const SEARCH_SECTION_ID = 'SEARCH_SECTION_ID';
export const SEARCH_ACTION_ID = 'SEARCH_ACTION_ID';
export const DISPLAY_SECTION_ID = 'DISPLAY_SECTION_ID';
export const DISPLAY_USER_GUIDANCE_ACTION_ID =
  'DISPLAY_USER_GUIDANCE_ACTION_ID';
export const DISPLAY_ENABLE_TRACK_CHANGES_ACTION_ID =
  'DISPLAY_ENABLE_TRACK_CHANGES_ACTION_ID';
export const DISPLAY_TOGGLE_TRACK_CHANGES_ACTION_ID =
  'DISPLAY_TOGGLE_TRACK_CHANGES_ACTION_ID';
export const STRUCTURE_SECTION_ID = 'STRUCTURE_SECTION_ID';
export const STRUCTURE_CHANGE_ANNEX_STRUCTURE_ID =
  'STRUCTURE_CHANGE_ANNEX_STRUCTURE_ID';
export const STRUCTURE_RENUMBER_DOCUMENT_ID = 'STRUCTURE_RENUMBER_DOCUMENT_ID';
export const RELOAD_SECTION_ID = 'RELOAD_SECTION_ID';
export const RELOAD_SECTION_RELOAD_ACTION_ID =
  'RELOAD_SECTION_RELOAD_ACTION_ID';
export const COMPARE_SECTION_ID = 'COMPARE_SECTION_ID';
export const COMPARE_NEXT_CHANGE_ACTION_ID = 'COMPARE_NEXT_CHANGE_ID';
export const COMPARE_PREV_CHANGE_ACTION_ID = 'COMPARE_PREV_CHANGE_ID';
export const COMPARE_SYNC_PANELS_ACTION = 'COMPARE_SYNC_PANELS';
export const COMPARE_EXPORT_DROPDOWN_ID = 'COMPARE_EXPORT_DROPDOWN_ID';
export const COMPARE_EXPORT_DROPDOWN_EXPORT_PDF =
  'COMPARE_EXPORT_DROPDOWN_EXPORT_PDF';
export const COMPARE_EXPORT_DROPDOWN_EXPORT_XML =
  'COMPARE_EXPORT_DROPDOWN_EXPORT_XML';
export const COMPARE_EXPORT_DROPDOWN_EXPORT_DOCUWRITE =
  'COMPARE_EXPORT_DROPDOWN_EXPORT_DOCUWRITE';
export const VIEW_VERSION_SECTION_ID = 'VIEW_VERSION_SECTION_ID';
export const VIEW_SYNC_PANELS_ACTION = 'VIEW_SYNC_PANELS';
